OSGeo/grass-addons

README.md

The README deserves probably a broader update?!

Convert README to markdown with some updates

---

grass7/raster/r.hazard.flood/r.hazard.flood.py

This module does not operate in LatLong locations - tell it to the user.

r.hazard.flood: test added if in LatLong location

---

grass7/raster/r.flowfill/Makefile
grass7/raster/r.flowfill/r.flowfill.html
grass7/raster/r.flowfill/r.flowfill.py

I tested this on local repos and am now merging it into the general grass-addons repo.
This module routes flow across the surface, filling depressions where there is enough runoff:
https://www.earth-surf-dynam-discuss.net/esurf-2019-11/

Import r.flowfill

---

grass7/raster/r.sun.hourly/r.sun.hourly.py

Since it's using mode 1 or r.sun, the units are W/m2, not Wh/m2.

r.sun.hourly: fix units in documentation

---

grass7/imagery/i.spec.unmix/open.c

- fix potential buffer overflow (esp. expected in comment lines)
- more detailed warnings on reading spectrum matrix file

fix potential buffer overflow

---

grass7/raster/r.zonal.classes/r.zonal.classes.html

The table was not well rendered using the html tag. Now imbended in a "code" div and shortened.

rzonalclasses html fix table

---

grass7/raster/r.green/r.green.biomassfor/libforest/harvesting.py
grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.co2/r.green.biomassfor.co2.py
grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.impact/r.green.biomassfor.impact.py
grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.legal/r.green.biomassfor.legal.py
grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.recommended/r.green.biomassfor.recommended.py
grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.technical/r.green.biomassfor.technical.py
grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.theoretical/r.green.biomassfor.theoretical.py
grass7/raster/r.green/r.green.hydro/libhydro/basin.py
grass7/raster/r.green/r.green.hydro/r.green.hydro.closest/r.green.hydro.closest.py
grass7/raster/r.green/r.green.hydro/r.green.hydro.technical/r.green.hydro.technical.py
grass7/raster/r.green/r.green.install/r.green.install.py

Add support for both python2 and python3.

python2 and python3 support

---

grass7/vector/v.lidar.mcc/v.lidar.mcc.py

`file` is not available in python 3, use `open`

wqfile -> open

---

grass7/raster/r.in.srtm.region/r.in.srtm.region.py

Please review, not sure if this change is sufficient

WIP: update of urllib2 usage to Python 3

---

grass7/raster/r.in.pdal/r.in.pdal.py

- either use resolution or raster map/file reference (mutually exclusive)
- use PID in tmp name
- cleanup of raster file reference upon command termination

r.in.pdal addon: fix raster alignment

---

grass7/vector/v.class.mlR/v.class.mlR.html
grass7/vector/v.class.mlR/v.class.mlR.py

This pull request adds a series of new features. These include:
- more classifiers
- feature selection using RFE on random forest model
- the option to save and to load a trained model
- optional output of variable importance

Significative enhancement of v.class.mlR 

---

grass7/raster/r.mapcalc.tiled/Makefile
grass7/raster/r.mapcalc.tiled/r.mapcalc.tiled.html
grass7/raster/r.mapcalc.tiled/r.mapcalc.tiled.py

This pull request proposes a new addon module which cuts a raster input map into tiles and runs r.mapcalc over these tiles before patching the result together into a single output raster map. It is just a simple wrapper over GridModule.

Newaddon r mapcalc tiled

---

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py

- I changes the code so that the polygon of the map of AOI is used instead of only the region of this map
Is it okay to replace the region part or should I use a flag for the polygon or region variant?

i.sentinel.download: using the polygon of the map instead of the region

---

grass7/raster/r.in.usgs/r.in.usgs.py

If extracted files or raster maps are present (currently preserved only with -k flag),
use them in the import process.
This also improved and fixes several error and info messages, e.g. for cases
when there is no space left on the device and reports the state when no tiles are present
for patching.

r.in.usgs: reuse extracted .img files and imported rasters

---

grass7/raster/r.in.usgs/r.in.usgs.py

Using approach from g.extension in core (OSGeo/grass 86fbd098bb8f9f).

r.in.usgs: compatibility with Python 3 (urllib)

---

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py

Address: https://trac.osgeo.org/grass/ticket/3979

fix write_metadata and o-flag

---

grass7/raster/r.learn.ml/r.learn.ml.html
grass7/raster/r.learn.ml/r.learn.ml.py

r.learn.ml silently ignores to output validation files if not all input is given correctly. This PR adds checks for that.

r.learn.ml: more checks for user input

---

grass7/raster/r.in.usgs/r.in.usgs.py

In case there are tiles skipped at the end of the list (while continue),
we need to check for running processes and join if we are at the end of
the loop, otherwise we leave processes behind which may not be finished
in time for further use and will try to communicate with the manager
when it does not exist anymore.
Also adding early check and a message with suggested next step
for case when the directory for files does not exist.

r.in.usgs: Do not leave processes behind

---

grass7/raster/r.in.srtm.region/r.in.srtm.region.py

Set region to support also locations with not longlat projection.
Depending on the change in r.in.srtm (https://github.com/OSGeo/grass/pull/194).

r.in.srtm.region: support also locations with not longlat projection

---

grass7/raster/r.category.trim/r.category.trim.py

Attempt for updating the command, using the 2to3 tool.
Please verify/modify as needed.

r.category.trim addon: update to Python 3

---

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.html
grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py

With extent=region the import can be reduced to the current region rather than full scene import.

i.sentinel.import: added extent parameter

---

grass7/imagery/i.segment.stats/i.segment.stats.py

The previous implementation of handling null values in the input rasters did not work when a mask was used and the way rasters were deleted from the list also lead to skipping some of the other rasters.

i.segment.stats: improved handling of null values in raster inputs

---

grass7/vector/v.krige/Makefile
grass7/vector/v.krige/v.krige.py
grass7/vector/v.krige/vkrige_wxgui.py

trivial change to avoid file name confusion

v.krige: rename vkrige.py to vkrige_wxgui.py

---

grass7/raster/r.sim.terrain/r.sim.terrain.py

Fixed bug in net difference calculation, added copy elevation to current mapset to prevent temporal framework registration error, and refactored code.

updated r.sim.terrain

---

grass7/temporal/t.upgrade/Makefile
grass7/temporal/t.upgrade/t.upgrade.html
grass7/temporal/t.upgrade/t.upgrade.py

Developed based on https://github.com/OSGeo/grass/pull/130
It requires https://github.com/OSGeo/grass/pull/130 to be merged.

t.upgrade addon for TGIS DB version upgrade

---

grass7/display/d.vect.thematic2/d.vect.thematic2.py
grass7/imagery/i.landsat8.swlst/column_water_vapor.py
grass7/imagery/i.segment.hierarchical/isegpatch.py
grass7/raster/r.agent/libagent/ant.py
grass7/raster/r.droka/r.droka.py
grass7/raster/r.exdet/r.exdet.py
grass7/raster/r.meb/r.meb.py
grass7/raster/r.mess/r.mess.py
grass7/raster/r.recode.attr/r.recode.attr.py
grass7/vector/v.stream.order/v.stream.order.py

With this change both Python 2's `xrange()` and Python 3's `range()` are accommodated.

Python 3: xrange compatibility fix

---

grass7/raster/r.mwprecip/r.mwprecip.py

r.mwprecip addon: reformatting

---

grass7/raster/r.accumulate/main.c

Support for vectors in other mapsets

r.accumulate: Use vector db connection rather than the default one

---

grass7/display/d.vect.thematic2/d.vect.thematic2.py
grass7/general/g.cloud/g.cloud.py
grass7/general/g.proj.identify/g.proj.identify.py
grass7/imagery/i.fusion.brovey/i.fusion.brovey.py
grass7/imagery/i.ortho.corr/i.ortho.corr.py
grass7/misc/m.printws/m.printws.py
grass7/raster/r.cell.area/r.cell.area.py
grass7/raster/r.denoise/r.denoise.py
grass7/raster/r.fuzzy.logic/r.fuzzy.logic.html
grass7/raster/r.in.wcs/r.in.wcs.py
grass7/raster/r.mblend/r.mblend.py
grass7/raster/r.mcda.topsis/r.mcda.topsis.py
grass7/raster/r.series.diversity/r.series.diversity.py
grass7/raster/r.slope.direction/r.slope.direction.html
grass7/vector/v.mapcalc/v.mapcalc.py
grass7/vector/v.maxent.swd/v.maxent.swd.py
grass7/vector/v.what.spoly/v.what.spoly.py

- tab/space indentation mess fixed
- print() fixes
- HTML code fixes

addons: Python 3 reformatting

---

grass7/raster/r.lfp/r.lfp.py

Revision is not int anymore. Just use try exception for writing history.

r.lfp: revision is not int anymore

---

grass7/raster/r.slope.direction/r.slope.direction.html

Should fix the build of the manual...

Replace norwegian character

---

grass7/vector/v.rast.bufferstats/v.rast.bufferstats.py

Some improvements in v.rast.bufferstats

Bufferstats

---

grass7/raster/r.colors.out_sld/r.colors.out_sld.py

Implementing Annas suggestion (thanks for the valuable insight BTW) 
Replace #102
Fix #101

r.colors.out_sld: write unicode in bytes mode

---

grass7/temporal/t.rast.kappa/t.rast.kappa.py

t.rast.kappa: fix import typo

---

grass7/raster/r.in.usgs/r.in.usgs.html
grass7/raster/r.in.usgs/r.in.usgs.py

fixes resolution handling for lidar and removes NLCD from options

r.in.usgs update

---

grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py

I have modified the code in order to manage the cases in which no clouds or shadows are detected. In this way, the issue #85 should be solved.

i.sentinel.mask: improved control checks about the number of clouds and shadows detected

---

grass7/raster/r.confusionmatrix/Makefile
grass7/raster/r.confusionmatrix/r.confusionmatrix.html
grass7/raster/r.confusionmatrix/r.confusionmatrix.py

Add a Addons which parses r.kappa and computes user and producer accuracies additionally.

r.confusionmatrix

---

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py

Round Sentinel-2 bands to CELL in case of reprojection.
Fixes #127

i.sentinel.import addon: round to CELL

---

grass7/imagery/i.histo.match/i.histo.match.py

i.histo.match Python3 compatible

---

roadmap/grass_roadmap.svg

trivial change to avoid hardcoded local paths

grass_roadmap: fix all paths to relative paths

---

grass7/vector/v.rast.bufferstats/v.rast.bufferstats.html
grass7/vector/v.rast.bufferstats/v.rast.bufferstats.py

- improved MASK handling
- improved category extraction for raster maps with categories assigned
- improved cleanup
Possible further improvements (maybe in a follow up PR):
- implementation of where option
- limit tabulation to area within buffer

v.rast.bufferstats: various further enhancements

---

grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py

I have updated the i.sentinel.mask.py file in order to remove at the end of the process all the *_double file created with the -s flag as requested by @veroandreo in #140

Update i.sentinel.mask.py in order to remove rescaled files (*_double) 

---

grass7/imagery/i.modis/i.modis.html

(they changes again without redirect...)

i.modis: LPDAAC url updates

---

grass7/imagery/i.histo.match/i.histo.match.py

i.histo.match

---

grass7/raster/r.learn.ml2/r.learn.ml2.html
grass7/raster/r.learn.ml2/r.learn.predict/r.learn.predict.html
grass7/raster/r.learn.ml2/r.learn.predict/r.learn.predict.py
grass7/raster/r.learn.ml2/r.learn.train/r.learn.train.html
grass7/raster/r.learn.ml2/r.learn.train/r.learn.train.py

Just cosmetics (pls update also in the master repo https://github.com/stevenpawley/r.learn.ml2 as needed)

r.learn.ml2: minor msg sync

---

grass7/raster/r.mapcalc.tiled/tests/config.ini
grass7/raster/r.mapcalc.tiled/tests/readme.md
grass7/raster/r.mapcalc.tiled/tests/test.py
grass7/raster/r.mapcalc.tiled/tests/visualization.py

Added Python scripts to execute and visualize a performance test r.mapcalc.tiled vs r.mapcalc.

r.mapcalc.tiled: add performance test

---

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py

footprints returned by sentinelsat can be polygons or multi-polygons: polygons are converted to multi-polygons  
coordinates of footprints need to be snapped (fp precision issues)

i.sentinel.download: fix footprints

---

grass7/raster/r.accumulate/calculate_lfp.c
grass7/raster/r.accumulate/global.h
grass7/raster/r.accumulate/line_list.c
grass7/raster/r.accumulate/point_list.c

Don't create lines during recursion; just find headwater points and trace down after recursion

r.accumulate: Improve performance

---

grass7/imagery/i.fusion.hpf/i.fusion.hpf.py

Follows https://github.com/NikosAlexandris/i.fusion.hpf/pull/15

i.fusion.hpf: simplify raster_history call

---

CONTRIBUTING.md

File derived from https://github.com/OSGeo/grass/blob/master/CONTRIBUTING.md
Fixes #173

CONTRIBUTING.md: added for Addons

---

grass7/imagery/i.zero2null/Makefile
grass7/imagery/i.zero2null/i.zero2null.html
grass7/imagery/i.zero2null/i.zero2null.py

fix nodata encoding for Sentinel-2 imagery, and possibly others
the value zero does not make sense for reflectance being the proportion of incoming light reflected back
zero is only possible for absolute black, all incoming light is completely absorbed (black holes can do that)

i.zero2null

---

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py

incomplete except/try for sentinelsat library presence

---

grass7/gui/wxpython/wx.metadata/README.md
grass7/gui/wxpython/wx.metadata/config/init_md.txt
grass7/gui/wxpython/wx.metadata/db.csw.admin/db.csw.admin.py
grass7/gui/wxpython/wx.metadata/db.csw.harvest/db.csw.harvest.py
grass7/gui/wxpython/wx.metadata/db.csw.run/db.csw.run.py
grass7/gui/wxpython/wx.metadata/dependency.py
grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py
grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py
grass7/gui/wxpython/wx.metadata/mdlib/cswutil.py
grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py
grass7/gui/wxpython/wx.metadata/mdlib/mdjinjaparser.py
grass7/gui/wxpython/wx.metadata/mdlib/mdpdffactory.py
grass7/gui/wxpython/wx.metadata/mdlib/mdpdftheme.py
grass7/gui/wxpython/wx.metadata/mdlib/mdutil.py
grass7/gui/wxpython/wx.metadata/r.info.iso/r.info.iso.py
grass7/gui/wxpython/wx.metadata/v.info.iso/v.info.iso.py

- initial update attempt
TODO: update wxPython code
Related documentation: https://grasswiki.osgeo.org/wiki/ISO/INSPIRE_Metadata_Support

wx.metadata: update to Python 3

---

grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.html
grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py

- predefine path to S2 band json file
- update of example (metadata json file usage simplified)
- minor parameter descriptions
(fixes #143)
Co-Authored-By: @AnikaBettge <bettge@mundialis.de>

i.sentinel.mask: predefine path to S2 band json file

---

grass7/imagery/i.sentinel.mask/Makefile
grass7/imagery/i.sentinel.preproc/Makefile

note: code is found in `./i.sentinel/`

remove unused empty dirs

---

tools/cronjobs_osgeo_lxd/compile_addons_git.sh
tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass78_src_relbr78_snapshot.sh
tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_src_snapshot.sh
tools/cronjobs_osgeo_lxd/cron_job_list_grass
tools/cronjobs_osgeo_lxd/get_page_description.py
tools/cronjobs_osgeo_lxd/googleebda3c3d501e9945.html
tools/cronjobs_osgeo_lxd/grass-addons-index.sh
tools/cronjobs_osgeo_lxd/hugo_clean_and_update_job.sh
tools/cronjobs_osgeo_lxd/rsyncd.conf
tools/cronjobs_osgeo_lxd/rsyncd.motd

scripts to compile on grasslxd server:
- hugo based web pages
- source code weekly snapshots
- Linux binary weekly snapshots
- addon manuals
- programmer's manual
rsync configuration for mirrors
Fixes https://github.com/OSGeo/grass-website/issues/171

grasslxd server: cronjobs hugo, snapshots, progman, addon manuals

---

grass7/raster/r.accumulate/accumulate.c
grass7/raster/r.accumulate/calculate_lfp_iterative.c
grass7/raster/r.accumulate/calculate_lfp_recursive.c
grass7/raster/r.accumulate/delineate_streams.c
grass7/raster/r.accumulate/delineate_subwatersheds.c
grass7/raster/r.accumulate/global.h
grass7/raster/r.accumulate/main.c
grass7/raster/r.accumulate/subaccumulate.c

* Localize done arrays
* Rename rows, cols to nrows, ncols
* Static window, nrows, ncols

Refactoring r.accumulate

---

grass7/display/d.vect.colbp/d.vect.colbp.py
grass7/display/d.vect.colhist/d.vect.colhist.py
grass7/imagery/i.variance/i.variance.py
grass7/raster/r.colors.matplotlib/r.colors.matplotlib.py
grass7/raster/r.flowfill/r.flowfill.py
grass7/raster/r.hypso/r.hypso.py
grass7/raster/r.mwprecip/r.mwprecip.py
grass7/raster/r.object.activelearning/r.object.activelearning.py
grass7/raster/r.richdem.breachdepressions/r.richdem.breachdepressions.py
grass7/raster/r.richdem.filldepressions/r.richdem.filldepressions.py
grass7/raster/r.richdem.flowaccumulation/r.richdem.flowaccumulation.py
grass7/raster/r.richdem.resolveflats/r.richdem.resolveflats.py
grass7/raster/r.richdem.terrainattribute/r.richdem.terrainattribute.py
grass7/raster/r.width.funct/r.width.funct.py
grass7/vector/v.faultdirections/v.faultdirections.py
grass7/vector/v.in.pygbif/v.in.pygbif.py
grass7/vector/v.stream.profiler/v.stream.profiler.py

This PR fixes some issues related to lazy import.
See https://grass.osgeo.org/addons/grass7/logs/

force lazy import where possible

---

grass7/raster/r.landscape.evol/r.landscape.evol.html

r.landscape.evol manual: fix broken HTML chars

---

grass7/gui/wxpython/wx.metadata/config/connections_resources.xml

- deduplicate
- put country name first
Partially addresses #229

wx.metadata: update of some CSW urls

---

grass7/gui/wxpython/wx.metadata/dependency.py

wx.metadata: Fix syntax

---

grass7/raster/r.accumulate/calculate_lfp_iterative.c
grass7/raster/r.accumulate/calculate_lfp_recursive.c
grass7/raster/r.accumulate/delineate_streams.c
grass7/raster/r.accumulate/delineate_subwatersheds_iterative.c
grass7/raster/r.accumulate/delineate_subwatersheds_recursive.c

Add more checks for potential flow loops in the flow direction map

r.accumulate: flow loop checks

---

grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py

Fix save/cancel new csw connection.

wx.metadata/g.gui.cswbrowser: Fix save/cancel new csw connection

---

grass7/raster/r.in.usgs/r.in.usgs.py

r.in.usgs: move functions to top level to fix python pickling on windows

---

grass7/imagery/i.modis/i.modis.download/i.modis.download.html
grass7/imagery/i.modis/i.modis.download/i.modis.download.py

Update also the link to the tile map

i.modis.download: fixes for python3 and no date input

---

grass7/raster/r.accumulate/r.accumulate.html

Add the full citable reference to the longest flow path method.

r.accumulate: Add the full reference to the article

---

grass7/raster/r.agent/libagent/ant.py
grass7/raster/r.agent/libagent/anthill.py
grass7/raster/r.agent/libagent/grassland.py
grass7/raster/r.agent/libagent/playground.py
grass7/raster/r.agent/libagent/world.py

Resolves the following py modules import error in the [Trac ticket 2968](https://trac.osgeo.org/grass/ticket/2968).

r.agent: Fix import py modules from libagent lib

---

grass7/raster/r.sample.category/r.sample.category.html

since 6f46c2e3b55f1c685492779ed6ec644641009ac6

r.sample.category: remove known issue as it no longer applies

---

tools/cronjobs_osgeo_lxd/cron_grass74_releasebranch_74_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass74_src_relbr74_snapshot.sh
tools/cronjobs_osgeo_lxd/cron_grass76_releasebranch_76_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass76_src_relbr76_snapshot.sh

added for the sake of completeness

cronjobs: added G7.4 and G7.6 cronjobs

---

grass7/raster/r.confusionmatrix/r.confusionmatrix.py
grass7/raster/r.confusionmatrix/testsuite/data/confusionmatrix_raster_matrix.csv
grass7/raster/r.confusionmatrix/testsuite/test_r_confusionmatrix.py

Until now the commission error was written in the matrix 2 times. Now on is replaced by the omission error.
Added test using a raster_reference.

r.confusionmatrix: fix omission in matrix

---

grass7/raster/r.accumulate/delineate_subwatersheds_iterative.c

Minor refactoring to change the order of row, col, and id arguments for consistency

r.accumulate: Consistent order of row, col, id

---

grass7/gui/wxpython/wx.metadata/m.csw.update/m.csw.update.py

wx.metadata/m.csw.update: fix strip URL string

---

grass7/gui/wxpython/wx.metadata/m.csw.update/m.csw.update.py

wx.metadata/m.csw.update: fix exlusive flags rules

---

grass7/gui/wxpython/wx.metadata/m.csw.update/m.csw.update.py

Import 'urllib.request' py module as 'urlrequest'.

wx.metadata/m.csw.update: import 'urllib.request' py module as 'urlrequest'

---

grass7/gui/wxpython/wx.metadata/config/connections_resources.xml

Update CSW connection resource candidates, source is:
https://jeodpp.jrc.ec.europa.eu/ftp/jrc-opendata/APIS4DGOV/cases/LATEST/API-cases.ods

wx.metadata/config: update CSW connection resource candidates

---

grass7/gui/wxpython/wx.metadata/db.csw.admin/db.csw.admin.py

wx.metadata/db.csw.admin: fix import 'pycsw' py module

---

grass7/general/g.proj.identify/g.proj.identify.py

Remove duplicate 'osr' py module import.

g.proj.identify: remove duplicate 'osr' py module import

---

grass7/vector/v.link.precip/v.link.precip.py

Fix 'IOError' exception.
```
Compiling...
File "/tmp/grass7-tomas-5934/tmp33nrxzle/v.link.precip/scripts/v.link.precip", line 120
except IOError as (errno,strerror):
^
SyntaxError: invalid syntax
make: *** [/usr/lib64/grass79/include/Make/Html.make:14: v.link.precip.tmp.html] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
```

v.link.precip: fix 'IOError' exception

---

grass7/vector/v.what.strds.timestamp/v.what.strds.timestamp.py

change inequality signs in v.what.strds.timestamp

---

grass7/vector/v.db.pyupdate/Makefile
grass7/vector/v.db.pyupdate/testsuite/test_v_db_pyupdate.py
grass7/vector/v.db.pyupdate/v.db.pyupdate.html
grass7/vector/v.db.pyupdate/v.db.pyupdate.py

Uses v.db.select JSON output, Python eval and exec, and db.execute to compute new attributes.

v.db.pyupdate: Update vector attributes with Python

---

tools/cronjobs_osgeo_lxd/compile_addons_git.sh

tools/compile_addons_git.sh: call explicitly with bash

---

grass7/raster/r.in.wcs/r.in.wcs.py

r.in.wcs: fix decode string

---

grass7/vector/v.what.strds.timestamp/v.what.strds.timestamp.html

Add an example based on North Carolina LST time series (toDo: add test using the example...)

v.what.strds.timestamp: add example

---

tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_build_bins.sh

manual compilation: activate liblas

---

grass7/raster/r.sun.daily/r.sun.daily.py

Add insol_time parameter to get the total insolation time between two dates.
Should close https://github.com/OSGeo/grass-addons/issues/325

Add insol_time parameter to r.sun.daily

---

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py

Correction of `-j` description

i.sentinel.import: fix -j description

---

tools/create_manuals_sitemap.py

This should be the first step for https://github.com/OSGeo/grass-website/issues/226

added tool to create manuals sitemap

---

tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh

Generates in cronjob
- https://grass.osgeo.org/grass78/manuals/sitemap_manuals.xml
- https://grass.osgeo.org/grass78/manuals/addons/sitemap_manuals.xml
- https://grass.osgeo.org/grass79/manuals/sitemap_manuals.xml
Needed for https://github.com/OSGeo/grass-website/pull/230

cronjob: generate manual sitemaps

---

tools/create_manuals_sitemap.py

run only in a folder, not only in addons subfolder if present

create_manuals_sitemap.py: simplified code

---

tools/cronjobs_osgeo_lxd/hugo_clean_and_update_job.sh

this should be the last step for https://github.com/OSGeo/grass-website/issues/226, it require the merge of OSGeo/grass-website/pull/230

hugo cronjob: link sitemap.xml from file folder to main dir

---

grass7/vector/v.db.pyupdate/v.db.pyupdate.py

JSON output from v.db.select is available only after 7.8.
Parse the simplified CSV from v.db.pyupdate instead.

v.db.pyupdate: Support also v7.8

---

grass7/imagery/i.landsat/Makefile
grass7/imagery/i.landsat/i.landsat.download/Makefile
grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html
grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.py
grass7/imagery/i.landsat/i.landsat.html
grass7/imagery/i.landsat/i.landsat.import/Makefile
grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.html
grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py

In this PR I'm adding 2 new addons: i.landsat.download and i.landsat.import

New addon: i.landsat toolset

---

grass7/vector/v.what.strds.timestamp/v.what.strds.timestamp.py

* fix a crashing module
* fix #378

v.what.strds.timestamp: skip empty STRDS with a warning message

---

grass7/raster/r.accumulate/r.accumulate.html

* Typo: `rune` => `run`
* Reformat the flow accumulation comparison

r.accumulate: Update the manual

---

grass7/vector/v.in.csv/Makefile
grass7/vector/v.in.csv/v.in.csv.html
grass7/vector/v.in.csv/v.in.csv.py

Imports CSV as vector points with reprojection using Python pyproj package.
Fixes column names in the header, can limit number of imported lines,
allows to set column types as integers or floats by specifying
column names.

v.in.csv: Easy import of CSV as vector points

---

grass7/vector/v.transects/v.transects.py

This should fix #400 It still runs with Python2.
@gioman could you please test?

v.transects: make module Python3 compliant

---

grass7/vector/v.in.survey/v.in.survey.py

v.in.survey: module startup fix

---

grass7/raster/r.valley.bottom/r.valley.bottom.py

I've made some tweaks to the r.valley.bottom module; it is faster now by using simpler r.mapcalc statements for the elevation percentile, and I've cleaned-up / commented the code. I've also cut down the large number of messages which were sent to the grass console, instead providing a more concise summary similar to what SAGA-GIS provides. Otherwise the output MrVBF/MrRTF should be the same.

r.valley.bottom performance improvements

---

grass7/imagery/i.modis/i.modis.download/i.modis.download.py

This PR clarifies `i.modis.download` error messages when:
1) settings file is not found
Current message: Folder to write downloaded files does not exist or is not writeable
New message: ERROR: Unable to read settings: [Errno 2] No such file or directory:
'settings/modis.txt'
2) settings file is not readble
Current message: Folder to write downloaded files does not exist or is not writeable
New message: ERROR: Unable to read settings: [Errno 13] Permission denied: 'modis.txt'
3) target folder is not not found
Current message: Folder to write downloaded files does not exist or is not writeable
New message: ERROR: Folder /tmp/modis3 does not exist
4) target folder is not writable
Current message: Folder to write downloaded files does not exist or is not writeable
New message: ERROR: Folder …

i.modis.download: fix error message when settings file not found

---

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py

@neteler, @anikaweinmann does it make sense to have producttype also here?
it was missing for my use case....

add option to i.sentinel.coverage

---

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html
grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py

This commit, to work properly and not return error, needs to modify also sentinelsat with this change https://github.com/sentinelsat/sentinelsat/pull/421

i.sentinel.download: add better support to LTA

---

grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py

**To Reproduce**
Steps to reproduce the behavior:
1. Launch Metadata editor `g.gui.metadata`
2. Try edit (Pencil tool) some vector / raster map metadata
3.  See error message
**Error message**
```
File "/home/tomas/.grass7/addons/scripts/g.gui.metadata", line 512, in onEdit
ok = self.editMapMetadata()
File "/home/tomas/.grass7/addons/scripts/g.gui.metadata", line 830, in editMapMetadata
self.mdCreator.createGrassInspireISO()
File "/home/tomas/.grass7/addons/etc/wx.metadata/mdlib/mdgrass.py", line 437, in createGrassInspireISO
self.createGrassBasicISO()
File "/home/tomas/.grass7/addons/etc/wx.metadata/mdlib/mdgrass.py", line 371, in createGrassBasicISO
epsg = self.getEPSG()
File "/home/tomas/.grass7/addons/etc/wx.metadata/mdlib/mdgrass.py", line 211, in …
```

wxGUI/wx.metadata: fix retrieval of projection information (get EPSG code)

---

grass7/raster/r.in.usgs/r.in.usgs.py

When file size stated in the API differs from the local file too much, do not fail and require user to re-run the module.
Instead, add it to the download list and continue the process.

r.in.usgs: Do not fail when file size differs

---

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.html

- update examples (some to NC sample dataset)
- mention t.sentinel

i.sentinel.coverage manual: improve examples

---

grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py

This PR implements @ninsbl  suggestion in https://github.com/veroandreo/i.landsat/issues/16#issuecomment-742844484 to use GDAL virtual file system and the tarfile library instead of shutil. This removes the need to untar files and then remove them. The `unzip_dir` option is no longer required either.

refactor i.landsat.import to use gdal virtual file system and tarfile library

---

grass7/raster/r.accumulate/accumulate_iterative.c
grass7/raster/r.accumulate/accumulate_recursive.c
grass7/raster/r.accumulate/main.c

I think null by default makes more sense even though it can be slower.

r.accumulate: Invert -N to -0

---

grass7/imagery/i.landsat/Makefile
grass7/imagery/i.landsat/i.landsat.qa/Makefile
grass7/imagery/i.landsat/i.landsat.qa/i.landsat.qa.html
grass7/imagery/i.landsat/i.landsat.qa/i.landsat.qa.py

A first rough attempt at fixing #441 with a more general module.
Should be easy to add support for collection 2.
Needs still a bit more work esp. on documentation...

i.landsat.qa: qa bands from landsat collection 1and 2

---

grass7/raster/r.learn.ml2/r.learn.train/r.learn.train.py

Reverts OSGeo/grass-addons#448

Revert "r.learn.train: fix for scikit-learn==0.24.0"

---

grass7/raster/r.basin/r.basin.py

fix for r.basin issue #443 due to a change in v.to.db behaviour

attempt to fix r.basin issue #443

---

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html

Followup to PR "add collection 2 support in i.landsat.download" #450 (must be merged first)

i.landsat.download manual: update to new product names

---

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html
grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.py

- add link to collection 2 info in the **SEE ALSO** section of the manual 
- add timeout also in the second call to `ee.download()` for the case of downloading selected scenes only.

i.landsat.download: minor changes

---

grass7/raster/r.sample.category/r.sample.category.py

r.sample.category write history

---

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html

Explain tiers; added acquisition years

i.landsat.download manual: more background info

---

grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py

is_dir() is not an attribute of os, the right function is os.path.isdir()

fix wrong function to check if folder is directory

---

grass7/vector/v.rast.bufferstats/v.rast.bufferstats.py

The change seems to be need in the case of rasters with categories name

v.rast.bufferstats: support for raster with categories

---

.github/workflows/build_grass.sh
.github/workflows/ci.yml
.github/workflows/extra_requirements.txt
grass7/vector/v.in.pygbif/v.in.pygbif.py

Adress #472
Would be good to document how to handle dependencies on external libraries for AddOn tests.
Maybe something for the evtl. GSoC project on testing framework?

add GDAL and pygbif to extra_requirements

---

grass7/imagery/i.modis/i.modis.download/i.modis.download.py
grass7/imagery/i.modis/libmodis/rmodislib.py

This PR adds monthly 1km vegetation index products to libmodis and i.modis.download

add mod13a3 and myd13a3 to libmodis and i.modis.download

---

grass7/vector/v.tin.to.rast/v.tin.to.rast.py

https://github.com/OSGeo/grass-addons/issues/515

v.tin.to.rast: Python fixes

---

tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass8_HEAD_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass8_HEAD_src_snapshot.sh
tools/cronjobs_osgeo_lxd/cron_job_list_grass

update to G80 after merge of https://github.com/OSGeo/grass/pull/1597

cronjobs: update to GRASS GIS 8.0.dev in core repo

---

grass7/vector/v.rast.bufferstats/v.rast.bufferstats.py

v.rast.bufferstats: fix buffer around areas, typo and use_label

---

grass7/general/g.projpicker/Makefile
grass7/general/g.projpicker/g.projpicker.html
grass7/general/g.projpicker/g.projpicker.py

Add the ProjPicker (https://github.com/HuidaeCho/projpicker) wrapper.
```bash
pip3 install projpicker
```

Add g.projpicker

---

grass7/imagery/i.modis/i.modis.html

Various MODIS products were missing from the manual page.
Added now.

i.modis manual: add missing products

---

grass7/raster/r.extract/r.extract.py

fixes
```
r.extract input=some_map output=othermap cats=3 --o
File "/home/mneteler/.grass7/addons/scripts/r.extract", line 116, in <module>
sys.exit(main())
File "/home/mneteler/.grass7/addons/scripts/r.extract", line 101, in main
output_tmp = gs.append_random("tmp", 8)
AttributeError: module 'grass.script' has no attribute 'append_random'
```

r.extract: fix AttributeError 'append_random'

---

grass7/general/g.projpicker/g.projpicker.html
grass7/general/g.projpicker/g.projpicker.py

* Add more explanations about quotes
* Tabs to spaces
* Add a period in the module description

g.projpicker: Improve the manual

---

grass7/raster/r.stream.basins/io.c
grass7/raster/r.stream.channel/io.c
grass7/raster/r.stream.distance/io.c
grass7/raster/r.stream.order/io.c
grass7/raster/r.stream.segment/io.c
grass7/raster/r.stream.slope/main.c
grass7/raster/r.stream.snap/io.c
grass7/raster/r.stream.stats/io.c

r.stream.*: Avoid comparing floating point numbers using not equal

---

grass7/raster/r.basin/r.basin.py

Resolve #484 by using raster, not the vector version of the same raster, to set the correct resolution.

r.basin: g.region using raster to set the correct resolution

---

src/raster/r.sim.terrain/r.sim.terrain.html
src/raster/r.sim.terrain/r.sim.terrain.py

**Changes**
- Fixed a bug for running 'series' mode
- Edge effect handling switched from r.grow.distance to r.slope.aspect's '-e' flag
- Switched to grass script's 'mapcalc' wrapper
- Switched from string formatting to f-strings where appropriate
- Applied Black formatting
- Updated troubleshooting in manual page
- Updated references in manual page
- Updated csv handling
- Fixed issues raised by @petrasovaa 's review
- Pull request  with upstream set to grass7 replaces #575

r.sim.terrain: bugfix, refactoring, docs

---

src/imagery/i.pysptools.unmix/i.pysptools.unmix.py

Fixed a typo in module documentation

Fixed Typo

---

src/raster/r.in.usgs/r.in.usgs.py

* Avoid all caps in messages.
* Improve consistency.
* Include relevant details.
* Include underlying error messages.
* Report about upcomming download, then show percentage, not the otherway around.
* Simplify if-statements by handling the error state in a if first, than continue without nesting (instead of if-else).

r.in.usgs: Improve text and placement of messages

---

src/raster/r.valley.bottom/r.valley.bottom.py

r.valley.bottom: use only API from GRASS 7.8 in grass7 branch

---

src/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
src/raster/r.valley.bottom/r.valley.bottom.py
src/vector/v.habitat.dem/v.habitat.dem.py

fix addons broken due to GRASS 8 modules API

---

.gitignore
CONTRIBUTING.md
README.md
src/imagery/i.cva/Makefile
src/vector/v.mapcalc/Makefile
src/vector/v.stream.profiler/Makefile

* Update from grass7 to grass8 in the contributing file.
* Update to v8 in the readme file or remove references to version completely.
* Remove from code some unnecessary, outdated, or broken references to v7 which are easy to solve.

Update to grass8 branch in contributing and readme

---

src/imagery/i.gabor/i.gabor.py
src/raster/r.agent/libagent/grassland.py
src/raster/r.droka/r.droka.py
src/raster/r.exdet/r.exdet.py
src/raster/r.fidimo/r.fidimo.py
src/raster/r.flexure/r.flexure.py
src/raster/r.flowfill/r.flowfill.py
src/raster/r.popgrowth/r.popgrowth.py
src/raster/r.richdem.breachdepressions/r.richdem.breachdepressions.py
src/raster/r.richdem.filldepressions/r.richdem.filldepressions.py
src/raster/r.richdem.flowaccumulation/r.richdem.flowaccumulation.py
src/raster/r.richdem.resolveflats/r.richdem.resolveflats.py

grass.script.array.read functions is deprecated and going away with G8.

replace use of deprecated grass.script.array.read api calls

---

tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass8_HEAD_build_bins.sh

* align grass-addons to the new layout [grass7 branch] (critical)
* use already defined vars (cosmetics)
* don't run distclean twice (cosmetics)
* fix ARCH variable (critical)
* remove unknown configure options (cosmetics)

fix cron_grass_build_bins scripts (78/80)

---

tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
tools/cronjobs_osgeo_lxd/cron_grass8_HEAD_build_bins.sh

fix cron_grass_build_bins scripts

---

utils/cronjobs_osgeo_lxd/check_addons_urls.sh

Simplify find source code and history URL.

utils/cronjobs_osgeo_lxd: simplify find source code and history URL

---

src/raster/r.connectivity/r.connectivity.corridors/r.connectivity.corridors.html
src/raster/r.connectivity/r.connectivity.corridors/r.connectivity.corridors.py
src/raster/r.connectivity/r.connectivity.distance/r.connectivity.distance.html
src/raster/r.connectivity/r.connectivity.distance/r.connectivity.distance.py
src/raster/r.connectivity/r.connectivity.network/r.connectivity.network.html
src/raster/r.connectivity/r.connectivity.network/r.connectivity.network.py

This is my first real contribution to the project, so I'm starting small with edits only for one module, the three algorithms in r.connectivity.*, to see how the process works out. These are language revisions only, no code changes. I'm using a text tool to help me, so what I change is when I'm pretty sure that there's an error, it's not out of my head.
I'd like some feedback on the best way to organize my commits/PRs if I would want to check multiple addons. Is one commit per addon, combined into one PR per type (raster, vector, temporal) too much?

r.connectivity.*: Spelling fixes

---

src/vector/v.what.rast.label/Makefile
src/vector/v.what.rast.label/v.what.rast.label.html
src/vector/v.what.rast.label/v.what.rast.label.py

Add-on to uploads raster values and labels at positions of vector points to the vector attribute tab

new addon v.what.rast.label

---

src/raster/r.out.maxent_swd/Makefile
src/raster/r.out.maxent_swd/r.out.maxent_swd.html
src/raster/r.out.maxent_swd/r.out.maxent_swd.py

Replaces #226
Suggested changes from review of #226 are integrated

r.out.maxent_swd: update to GRASS 7/8 and Python 3

---

src/raster/r.colors.out_sld/r.colors.out_sld.py

Adds a 1..10..20.. % count, useful for maps with huge amount of categories.
TODO: maybe it needs a rewrite to be more pythonic :-)

r.colors.out_sld: add percent counter

---

src/raster/r.colors.out_sld/r.colors.out_sld.py

- fixes missing linebreak
- minor title styling

r.colors.out_sld: minor XML formatting

---

src/vector/v.what.rast.label/v.what.rast.label.html

reformulation few lines in helpfile

v.what.rast.label manual: minor reformulation

---

.github/workflows/install_r_packages.R
src/raster/r.futures/r.futures.calib/r.futures.calib.py
src/raster/r.futures/r.futures.calib/testsuite/test_r_futures_calib.py
src/raster/r.futures/r.futures.devpressure/r.futures.devpressure.py
src/raster/r.futures/r.futures.devpressure/testsuite/test_r_futures_devpressure.py
src/raster/r.futures/r.futures.html
src/raster/r.futures/r.futures.pga/r.futures.pga.html
src/raster/r.futures/r.futures.potential/r.futures.potential.py
src/raster/r.futures/r.futures.potsurface/r.futures.potsurface.html

https://github.com/ncsu-landscape-dynamics/GRASS_FUTURES/releases/tag/v2.3.0

r.futures: update to version 2.3.0

---

src/raster/r.vif/r.vif.html
src/raster/r.vif/r.vif.py

bugfix (add -s flag to r.random)

r.vif: Add r.random seed handling

---

src/raster/r.random.weight/r.random.weight.py

string has no module replace, so I changed it in order to do a proper string replacement

r.random.weight: fix string.replace bug

---

src/vector/v.in.redlist/v.in.redlist.py

Deleted the "b" in line 105 and tested, to solve the bug https://github.com/OSGeo/grass-addons/issues/727

v.in.redlist: exporting text file of list of species

---

src/raster/r.viewshed.exposure/r.viewshed.exposure.html

- fix wrong tag
- HTML cosmetics
(found via inspection of https://grass.osgeo.org/addons/grass8/logs/)

r.viewshed.exposure manual: fix HTML

---

src/vector/v.tin.to.rast/v.tin.to.rast.py

v.tin.to.rast GRASS 8 compatibility

---

.github/workflows/ci.yml

* Add release branch for v8.2.

CI: Add v8.2 branch to test build and test run

---

utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh

- explain server preparation
- cleanup cruft leftover after `make distclean`

cron_grass8_relbranch_build_binaries.sh: comments updated

---

utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh

- added preparations procedure, on OSGeo server
- increment GMINOR to 3
- cleanup leftover added (bug in "make distclean"?)
- reset i18N POT files

cron_grass8_main_build_binaries.sh: GMINOR=3, preparations, cleanup

---

src/vector/v.tin.to.rast/v.tin.to.rast.html
src/vector/v.tin.to.rast/v.tin.to.rast.py

This PR adds a user example.
(review: @amuriy @antoalli (?))

v.tin.to.rast manual: add example

---

src/raster/r.boxplot/r.boxplot.html

Linux compilation failed (https://grass.osgeo.org/addons/grass8/logs/), not sure this empty heading has anything to do with it. Otherwise, @neteler do you have an idea why it is failing?

r.boxplot documentation bugfix

---

src/raster/r.boxplot/r.boxplot.py

Deal with cases in which the color table contains more categories as the
raster layer.
Deal with cases in which some but not all categories have a label.

r.boxplot improvements

---

utils/backport_po.sh

This script merges PO files from the main branch into a release branch for backporting messages.

Add backport_po.sh

---

utils/cronjobs_osgeo_lxd/cron_job_list_grass

Fixes wrong order submitted in #752

cronjob: fix order of minute hour

---

src/raster/r.mapcalc.tiled/r.mapcalc.tiled.html
src/raster/r.mapcalc.tiled/r.mapcalc.tiled.py

This needs https://github.com/OSGeo/grass/pull/2249 but it should work for older grass versions as well.

r.mapcalc.tiled: use parallelized r.patch if no overlap

---

src/raster/r.area.createweight/r.area.createweight.py

Due compilation error on OS MS Windows (missing some py packages). Fixes https://github.com/OSGeo/grass/issues/2492.

r.area.createweight: fix lazy import py packages

---

utils/cronjobs_osgeo_lxd/cron_grass8_main_src_snapshot.sh
utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_src_snapshot.sh

Source code tarball version bumps
- GRASS GIS relbranch 8.0 -> 8.2 (https://grass.osgeo.org/grass82/source/snapshot/)
- GRASS GIS main 8.1 -> 8.3 (https://grass.osgeo.org/grass83/source/snapshot/)
Completes #752

cronjobs: src tarball version bumps

---

src/raster/r.series.boxplot/r.series.boxplot.html

r.series.boxplot: remove errors

---

src/imagery/i.modis/i.modis.download/i.modis.download.html

Rewording of this manual snippet.

i.modis.download manual: expand USGS app authorization

---

src/raster/r.boxplot/r.boxplot.html
src/raster/r.boxplot/r.boxplot.py

Restructering code, added boxplot format options
Different default behaviour: module now always respects the region setting.

r.boxplot restructering code

---

utils/cronjobs_osgeo_lxd/robots.txt

Added file here for convenience.

robots.txt: added

---

src/temporal/t.rast.whatcsv/t.rast.whatcsv.py

t.rast.whatcsv: fix by using pygrass Module, not read_command

---

src/raster/r.in.usgs/r.in.usgs.py

* Use nprocs and memory for r.patch with >=8.2.
* Make the cache tolerance configurable and increase the default value.

r.in.usgs: Use parallel for patching, cache tolerance

---

src/raster/r.centroids/r.centroids.py
src/raster/r.centroids/testsuite/test_r_centroids.py
src/raster/r.sample.category/testsuite/test_numbers.sh

Additionally fix r.sample.category test by setting region.

r.centroids: Fix module and test

---

src/raster/r.bioclim/r.bioclim.html
src/raster/r.bioclim/r.bioclim.py

r.bioclim manual: update URL to Worldclim BIOCLIM

---

src/imagery/i.ann.maskrcnn/maskrcnnlib/model.py
src/imagery/i.ann.maskrcnn/maskrcnnlib/utils.py

See also: https://github.com/OSGeo/grass/issues/2601

i.ann.maskrcnn: remove deprecated distutils

---

src/raster/r.boxplot/r.boxplot.html
src/raster/r.boxplot/r.boxplot.py

Bugfix in how boxplot colors were handled when the -c flag was set

r.boxplot: bugfix

---

README.md
utils/check_examples_screenshots_tests.py
utils/cronjobs_osgeo_lxd/README.md
utils/cronjobs_osgeo_lxd/compile_addons_git.sh
utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
utils/savanna/savanna_copy_grass.sh
utils/savanna/savanna_mosaic_grass.sh
utils/savanna/savanna_mosaic_job.sh
utils/savanna/savanna_tiling_grass.sh
utils/std_dataset_display.py
utils/svnlog.sh

"Trivial" PR, typos identified with `grass_main/utils/fix_typos.sh` script and no code affected.
(https://github.com/OSGeo/grass/blob/main/utils/fix_typos.sh)

Fix various typos in comments

---

src/vector/v.in.redwg/entity.c
src/vector/v.in.redwg/main.c

This PR updates v.in.redwg to the latest https://github.com/LibreDWG/libredwg

v.in.redwg: Update to the latest libredwg

---

src/imagery/i.landsat/i.landsat.html
src/imagery/i.modis/i.modis.html
src/imagery/i.sentinel/i.sentinel.html
src/raster/r.connectivity/r.connectivity.html
src/raster/r.green/r.green.biomassfor/r.green.biomassfor.html
src/raster/r.green/r.green.gshp/r.green.gshp.html
src/raster/r.green/r.green.html
src/raster/r.green/r.green.hydro/r.green.hydro.html
src/raster/r.green/r.green.install/r.green.install.html
src/raster/r.in.ogc/r.in.ogc.html
src/vector/v.in.ogc/v.in.ogc.html

- title: use standard wording order
- fix file encoding declaration
- add viewport for mobile usage

manual: meta pages header fixes

---

src/raster/r.hants/r.hants.html

r.hants manual: explain HANTS acronym

---

utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh

CI: update GRASS GIS version in cronjob

---

grass7/raster/r.prominence/Makefile
grass7/raster/r.prominence/main.c
grass7/raster/r.prominence/r.prominence.html

This PR
- updates https://github.com/OSGeo/grass-addons/tree/grass6/src/raster/r.prominence to GRASS GIS 7/8
- indents the C code with https://github.com/OSGeo/grass/blob/master/utils/grass_indent.sh
- updates example to North Carolina sample data set
I have done shallow testing, using the new example.
Note: r.prominence appears to run very slow, perhaps there is potential to optimize that?

r.prominence: update from GRASS GIS 6 version
