OSGeo/grass-addons

grass7/raster/r.sample.category/r.sample.category.py
In python 3 maps do not have a length so the len of catlab has to be used from which the map is created.
=> r.sample.category: python3 compatible

grass7/raster/r.sample.category/r.sample.category.py, grass7/raster/r.sample.category/testsuite/test_numbers.sh
Adjust map() function to Python 3
Replace use of mask with r.reclass (now user mask can be present)
Add overwrite to test
Speedup by dropping r.univar and mask removal, (testsuite now finishes in 3 instead of 8 seconds on my laptop)
Testsuite runs successfully after changes
=> Py3, overwrite test, speedup

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.html, grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
This PR implements `raster_output` option into `i.sentinel.import`. In GRASS 7.9 also band references are stored into output register file.
```
i.sentinel.import input=data register_output=t_register.txt
t.register input=sentinel_ds input=t_register.txt
```
A register file typically contains two columns: imported raster map name and timestamp separated by |. In the case of current development version of GRASS which supports band references concept (see g.bands module for details) a register file is extended by a third column containg band reference information, see the examples below.
```
T33UVR_20181205T101401_B05|2018-12-05 10:16:43.275000
T33UVR_20181205T101401_B03|2018-12-05 10:16:43.275000
T33UVR_20181205T101401_B06|2018-12-05 10:16:43.275000
...
T33UVR_20181205T101401_B05|2018-12-05 …
```
=> i.sentinel.import: implement register_output option 

grass7/raster/Makefile, grass7/raster/r.zonal.classes/Makefile, grass7/raster/r.zonal.classes/r.zonal.classes, grass7/raster/r.zonal.classes/r.zonal.classes.html
I abide to RFC2.
Pull request for merge of a new addon called "r.zonal.classes" to the grass-addons repository. 
This addon computes class proportions and majority class of a "cover layer"  (e.g., a land cover map) according to how it intersects with areas/objects in a "base layer". This function is similar to what r.stats.zonal performs, but is intended to be used on integer values raster (CELL type) instead.
=> New addon "r.zonal.classes" for class proportion in raster areas

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
This PR fixes `i.sentinel.import` when creating `register_output` for Sentinel 2 L2A products. See #29
=> i.sentinel.import: fix register_output for S2 L2A products

grass7/imagery/i.fusion.hpf/constants.py
fixes "ValueError: 9 is not in list", issue https://github.com/NikosAlexandris/i.fusion.hpf/issues/14
=> Make MATRIX_PROPERTIES a list

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html
- added example of download Sentinel products by scene name (Sentinel file name)
- the query string sent to ESA can be shown with `--verbose`
=> i.sentinel.download manual: example download by scene name

grass7/raster/r.in.usgs/r.in.usgs.html, grass7/raster/r.in.usgs/r.in.usgs.py
Import and reprojection run in parallel. Assumes r.import which can run
in parallel (OSGeo/grass@fceba69). Parallelization is in batch which is
equal to the number of processes.
Exposes the memory option of r.import. 
Adds also better handling of HTTP errors and percentage output
for unzipping.
=> r.in.usgs: Parallel import

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
RFC 2616 HTTP/1.1 imposes a 2000 char limit on WKT when sent via HTTP GET (sentinelsat).
Raise fatal error when AOI map (-b flag) has too many vertices, recommending to use 'v.generalize' to simplify the boundaries.
=> i.sentinel.download: catch WKT too long with -b flag

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Since Sentinel scene name lookup from UUID is rather difficult, here a change to also include the names when -l listing Sentinel scenes.
Current version:
```
i.sentinel.download -l settings=~/.sentinel_esa producttype=S2MSI2A start=2018-03-01 end=2019-12-31 cloud=25 sort=ingestiondate map=kleve_krefeld_viersen_wesel_dp -b 
Generating WKT from AOI map (76 vertices)...
Sending WKT from AOI map to ESA...
Querying products: 100%|| 297/297 [00:12<00:00, 22.94 products/s]
297 Sentinel product(s) found
66421c1c-fb97-4379-9ffe-46d9096d5c65 2018-04-06T10:50:29Z  4% S2MSI2A
466c7407-5e0a-4abf-bf05-7bc482a6d8b7 2018-04-06T10:50:29Z  1% S2MSI2A
09d6cdee-77e3-495d-9c2b-228a8f892a81 2018-04-06T10:50:29Z 11% S2MSI2A
4edd776f-276b-4f5d-98f9-0ef7b18aa138 2018-04-06T10:50:29Z 10% S2MSI2A …
```
=> i.sentinel.download: -l flag list scene names

grass7/raster/r.null.all/Makefile, grass7/raster/r.null.all/r.null.all.html, grass7/raster/r.null.all/r.null.all.py
r.null.all uses g.list wrapper to select all raster maps or a subset.
g.list syntax options are supported but are driven by an option,
not flags with an explicit default value for selecting all maps.
r.null flags are supported as flags, but the dry run mode of r.null.all
does not take these into account.
=> r.null.all: add wrapper around r.null for multiple maps

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
The check at that early stage caused fatal errors when products did not contain cloud masks but the c-flag was set...
=> move check for file import

grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py, grass7/imagery/i.sentinel/i.sentinel.preproc/i.sentinel.preproc.py
Pass import parameters from i.sentinel.import and fix import issue
=> I sentinel preproc enhance

grass7/imagery/i.segment.stats/i.segment.stats.py
I don't remember why the csv output file was opened with 'wb', but in Python 3 this causes a TypeError when one tries to write a string to it.
Don't know if this is the right solution. If someone with more Python string handling notions than me sees an issue with this please shout out. Otherwise I'll commit soon.
=> Opening in byte creates problems in Python 3

grass7/imagery/i.sentinel/Makefile, grass7/raster/r.futures/Makefile
Approach following #30
If ok, also the Makefiles of 
- imagery/i.modis
- raster/r.futures
- raster/r.green
- raster/r.pi
to be updated accordingly.
=> Simplify Makefile to build all i.sentinel subdirs

grass7/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Currently `i.sentinel.import` unzips input data several times on single run when `-n` flags is not given. Potentially 4 times (import imagery files, cloud mask, write metadata, create register file)! This PR forces unzipping input data only on the beginning (when importing imagery files). 
BTW, I wonder why `-n` is not a default behaviour?
=> i.sentinel.import: avoid multiple unzipping on single run

grass7/imagery/i.modis/i.modis.import/i.modis.import.py, grass7/imagery/i.modis/libmodis/rmodislib.py
This PR fixes Python3-related issue of rmodislib. Currently `i.modis.download` fails with
```
File "/home/martin/.grass7/addons/scripts/i.modis.download", line 274, in <module>
sys.exit(main())
File "/home/martin/.grass7/addons/scripts/i.modis.download", line 246, in main
prod = product(produ).returned()
File "/home/martin/.grass7/addons/etc/i.modis/rmodislib.py", line 302, in returned
if self.products.keys().count(self.prod) == 1:
AttributeError: 'dict_keys' object has no attribute 'count'
```
Summary:
* dict_keys -> list
* string.find() to var.find()
* iteritems() -> items()
=> i.modis: fix python3 issues

grass7/raster/r.estimap.recreation/estimap_recreation/supply_and_use.py
Apparently this instruction
```
```
fails to pass through https://github.com/OSGeo/grass/blob/0a4d715a7e975b7508592566cae2aad636e8ac99/scripts/g.extension/g.extension.py#L1057
=> Remove '# -*- coding: utf-8 -*-' from supply_and_use.py

grass7/vector/v.centerline/v.centerline.py
Tested by clipping a small section of streams layer in nc_basic_spm_grass7.
Then that section was buffered and the buffer boundry was split at the ends,
creating two "bank lines". These lines were then used as input to v.centerline.
=> Adapt v.centerline for python 3

grass7/raster/r.richdem.breachdepressions/r.richdem.breachdepressions.py, grass7/raster/r.richdem.filldepressions/r.richdem.filldepressions.py, grass7/raster/r.richdem.flowaccumulation/r.richdem.flowaccumulation.py, grass7/raster/r.richdem.resolveflats/r.richdem.resolveflats.py, grass7/raster/r.richdem.terrainattribute/r.richdem.terrainattribute.py
Currently, manuals for r.richdem.* are not built because richdem cannot be imported on built server.
Lazy importing richdem should solve this...
=> r.richdem.*: lazy import RICHDEM so manuals get built

grass7/raster/r.maxent.lambdas/r.maxent.lambdas.html
* fix wrong encoding:
* `iconv -f ISO-8859 -t UTF-8 r.maxent.lambdas.html > new.html ; mv new.html r.maxent.lambdas.html`
* fix wrong HTML structure
=> r.maxent.lambdas manual: fix encoding and HTML

grass7/raster/r.edm.eval/r.edm.eval.html
now changed to UTF-8.
Should solve the compilation error as seen at https://wingrass.fsv.cvut.cz/grass78/x86_64/logs/
=> r.edm.eval manual: fix wrong encoding

grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py
Only computing the clouds does not need the mtd_file. For this the rules are modified
=> i.sentinel.mask fix parameter rules for only cloud computig

tools/addons/compile.sh
This might fix [#3818](https://trac.osgeo.org/grass/ticket/3818). I can't test this fix, but reviewing the code behind https://grass.osgeo.org/addons/grass7/modules.xml and comparing with similar code in  [g.extension.py:1317](https://github.com/OSGeo/grass/blob/ac8bd2777492fa11e3ab46b418f70fc01c5714a4/scripts/g.extension/g.extension.py#L1317) make me believe this can be the cause of the problem.
The modules.xml is generated along addon compilation on server, with log file inluding this double-man1 directory, see eg. https://grass.osgeo.org/addons/grass7/logs/db.join.log:
```
...
mkdir -p /tmp/.grass7/addons/db.join/docs/html
mkdir -p /tmp/.grass7/addons/db.join/docs/man/man1
mkdir -p /tmp/.grass7/addons/db.join/docs/man/man1/man1
mkdir -p /tmp/.grass7/addons/db.join/scripts
... …
```
=> Fix trac #3818 (bug in modules.xml: double man1 in path), possibly

grass7/vector/v.centerline/v.centerline.py
In the current version of `v.centerline` (with Python3) the variable `segment_input` is created using string formatting involving byte literals. Here the resulting `segment_input` is  `"P b'1' b'1'  50%"`; however this should be `"P 1 1  50%"` to be a valid input for the next step. The pull request adds an encoding step before the byte literal is used in `str.format().
Don't know how other python-based modules in GRASS handle byte literals involved in string formatting; or how how this is handeld in general. Seems to be related to python3; Maybe use case for new f-string-formatting? see also https://www.python.org/dev/peps/pep-0498/#no-binary-f-strings
=> change related to encoding of bytes literals used with str.format()

grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.py
When I call i.sentinel.mask only with shadow_raster without shadow_mask I got an error. This little change fixes it.
=> i.sentinel.mask: fix shadow_raster without shadow_mask

grass7/raster/r.learn.ml/r.learn.ml.py
Fix wrong syntax of `os.path.exists` in `r.learn.ml`
=> os.path_exists -> os.path.exists in r.learn.ml

grass7/raster/r.estimap.recreation/estimap_recreation/algorithm_description, grass7/raster/r.estimap.recreation/estimap_recreation/supply_and_use.py
For details, refer to https://gitlab.com/natcapes/r.estimap.recreation/-/commit/c0e2949d533829ddb42421504042e2918a79866a
=> Remove unicode characters that cause installation on Windows to fail

grass7/raster/r.fuzzy.logic/main.c, grass7/raster/r.fuzzy.logic/r.fuzzy.logic.html, grass7/raster/r.fuzzy.set/main.c, grass7/raster/r.fuzzy.set/r.fuzzy.set.html, grass7/raster/r.fuzzy.system/flood.map, grass7/raster/r.fuzzy.system/main.c, grass7/raster/r.fuzzy.system/r.fuzzy.system.html
I tried to clean up and clarify the documentation and examples for the r.fuzzy.{set,logic,system} addons, and made some minor bug fixes. 
This also closes #171. Core dump there was due to incorrect examples, nothing internal to the code itself.
Although the example code now runs, it does not produce the output shown as the example output. Furthermore, I think some code bugs still exist and will be opening new issues regarding them shortly. I think the example should also be simplified and depend only on core modules, not require other unnecessary addon modules.
=> Code and doc fixes for fuzzy addons

grass7/imagery/i.modis/i.modis.import/i.modis.import.py, grass7/imagery/i.modis/libmodis/rmodislib.py
`i.modis.import` with `input` parameter fails on Windows due to hardcoded Unix-like path separator.
=> fix i.modis.import on Windows (input parameter)

grass7/vector/v.delaunay3d/Makefile
The v.delaunay3d extension cannot be installed since bin/v.delaunay3d segfault.
```
> g.extension --verbose v.delaunay3d                                                                                                              ✔  10:19:12  
Fetching <v.delaunay3d> from GRASS GIS Addons repository (be patient)...
Downloading source code for <v.delaunay3d> from
<https://github.com/OSGeo/grass-addons/trunk/grass7/vector/v.delaunay3d>
which is identified as 'official' type of source...
A    v.delaunay3d
A    v.delaunay3d/Makefile
A    v.delaunay3d/local_proto.h
A    v.delaunay3d/main.cpp
A    v.delaunay3d/read.cpp
A    v.delaunay3d/v.delaunay3d.html
A    v.delaunay3d/write.cpp
Exporté à la révision 7646.
Compiling...
mkdir -p /tmp/grass7-lbartoletti-89056/tmp5pu0cfi_/v.delaunay3d/bin …
```
=> Fix v.delaunay3d compilation on FreeBSD

grass7/imagery/i.modis/i.modis.import/i.modis.import.py
Parameters `input/files` misuse.
```
> i.modis.import files=~/geodata/modis/MCD19A2.A2019030.h18v03.006.2019032034547.hdf 
[no input]
> i.modis.import input=~/geodata/modis/listfileMOD11A1.006.txt --o
WxPython missing, no GUI enabled
File "/home/martin/src/grass-addons/grass7/imagery/i.modis/i.modis.import/i.modis.import.py", line 621, in <module>
sys.exit(main())
File "/home/martin/src/grass-addons/grass7/imagery/i.modis/i.modis.import/i.modis.import.py", line 573, in main
single(options, remove, analyze, over, outfile)
File "/home/martin/src/grass-addons/grass7/imagery/i.modis/i.modis.import/i.modis.import.py", line 363, in single
pm = parseModis(hdf)
File "/usr/local/lib/python3.8/dist-packages/pymodis/parsemodis.py", line 70, in __init__
raise …
```
=> i.modis.import: improve error handling input/files

grass7/imagery/i.modis/i.modis.import/i.modis.import.py
```
i.modis.import input=~/geodata/modis/MCD19A2.A2019031.h18v03.006.2019036210121.hdf -t --o
ls *.tif -w1
MCD19A2.A2019031.h18v03.single_AOD_QA.tif
MCD19A2.A2019031.h18v03.single_Optical_Depth_055.tif
```
This is causing serious problem on Windows (here current working directory is set to C:\ by default).
=> i.modis.import: change cwd to input data dir

grass7/imagery/i.zero2null/i.zero2null.html
TODO: update scene name and UUID to one with no-data pixels
The idea was to use the scene indicated here: https://github.com/OSGeo/grass-addons/pull/123#issuecomment-619857619 
but there is some confusion with S2 name and UUID...
=> i.zero2null manual: example added

tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh, tools/cronjobs_osgeo_lxd/cron_grass78_src_relbr78_snapshot.sh, tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_build_bins.sh, tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_src_snapshot.sh
- fixes lack of updates due to wrong position of --exclude-vcs in tar command
- var name sync
=> cronjob grasslxd: fix broken tar flag order

grass7/raster/r.diversity/r.diversity.py
fix #233
Should work with both Python 2 and 3
=> r.diversity: open config file in non-bytes mode

grass7/gui/wxpython/wx.metadata/db.csw.admin/db.csw.admin.py, grass7/gui/wxpython/wx.metadata/dependency.py, grass7/gui/wxpython/wx.metadata/g.gui.cswbrowser/g.gui.cswbrowser.py, grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py, grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py, grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py, grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py, grass7/gui/wxpython/wx.metadata/mdlib/mdjinjaparser.py, grass7/gui/wxpython/wx.metadata/mdlib/mdpdffactory.py, grass7/gui/wxpython/wx.metadata/mdlib/mdpdftheme.py, grass7/gui/wxpython/wx.metadata/mdlib/mdutil.py, grass7/gui/wxpython/wx.metadata/r.info.iso/r.info.iso.py, grass7/gui/wxpython/wx.metadata/t.info.iso/t.info.iso.py, grass7/gui/wxpython/wx.metadata/v.info.iso/v.info.iso.py
1. wxGUI `g.gui.metadata`:
with csw dialog:
Exporting metadata reports to format PDF:
I changed the api to get static map img from google maps api to [osm api](https://github.com/jperelli/osm-static-maps) (sometimes the service `https://osm-static-maps.herokuapp.com` is unavailable for a short time). Currently only static map img url query `zoom` param argument is not correctly derived.
Example raster Basins maps (nc_basic_spm_grass7 location) url to get [static map img ](https://osm-static-maps.herokuapp.com/?geojson=[{'type':'Feature','geometry':{'type':'Polygon','coordinates':[[[-78.77462049,35.68792712],[-78.60889171,35.6875073],[-78.60830318,35.80918894],[-78.77428134,35.80960938],[-78.77462049,35.68792712]]]}}]&center=-78.69152414,35.74858701&zoom=12&size=200x200`) (Geographic …
=> wxGUI wx.metadata: Fix launch g.gui.metadata, g.gui.cswbrowser

grass7/raster/r.accumulate/accumulate.c, grass7/raster/r.accumulate/global.h, grass7/raster/r.accumulate/main.c
By default without the -N flag, flow accumulation is faster than with this flag. Nullifying cells with no flow accumulation (-N flag) adds too much overhead (`Rast_set_[cfd]_null_value` + null file). Subsequent analyses are not affected.
=> r.accumulate: Add -N flag for faster flow accumulation (with this flag is slower)

grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py
Default layout:
Expected layout:
=> wx.metadata/g.gui.metadata: Fix expand wx.SplitterWindow widget to the frame width size

grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py
Fix error message:
```
File "/home/tomas/.grass7/addons/scripts/g.gui.metadata", line 553, in onNewSession
self.MdDataCatalogPanelLeft.onChanged(None)
File "/home/tomas/.grass7/addons/scripts/g.gui.metadata", line 1208, in onChanged
item = self.GetSelection()
wx._core.wxAssertionError: C++ assertion "!HasFlag(wxTR_MULTIPLE)" failed at /usr/include/wx-3.0-gtk3/wx/generic/treectlg.h(115) in GetSelection(): must use GetSelections() with this control
```
=> wx.metadata/g.gui.metadata: Fix Spatial/Temporal maps wx.TreeCtrl widget GetSelections method name

grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py
To reproduce:
1. Launch wxGUI `g.gui.metadata`
2. Check 'Metadata extenal editor' wx.RadioButton widget
3. Check back 'Metadata map editor' wx.RadioButton widget
Default layout:
Expected layout:
=> wx.metadata/g.gui.metadata: Fix profile wx.ComboBox widget layout

grass7/gui/wxpython/wx.metadata/dependency.py
Add missing default dependencies py modules:
1.  `lxml`
2.  `pygments`
=> wx.metadata: Add missing default dependencies py modules

grass7/imagery/i.modis/i.modis.import/i.modis.import.py
Fix error by removing `"` and ` ` from band names:
```
WARNING: Illegal filename
<MOD13C2.A2015001.006.single_"CMG_0.05_Deg_Monthly_pixel_reliability">.
Character <"> not allowed.
...
```
Fixes #245
=> i.modis.import: fix broken import

grass7/vector/v.in.pygbif/testsuite/test_pygbif_import.py, grass7/vector/v.in.pygbif/v.in.pygbif.py
=> v.in.pygbif: Fix GDAL 3 related issues

grass7/raster/r.green/r.green.hydro/r.green.hydro.structure/r.green.hydro.structure.py
To reproduce:
`g.extension operation=add extension=r.green`
Error message (appear during compilation):
```
File "/tmp/grass7-tomas-21163/tmp2qtx71zh/r.green/scripts/r.green.hydro.structure", line 139, in <module>
from libgreen.checkparameter import check_required_columns, exception2error
ModuleNotFoundError: No module named 'libgreen'
```
=> r.green/r.green.hydro: Fix import py modules from libhydro, libgreen lib

grass7/raster/r.colors.out_sld/r.colors.out_sld.html, grass7/raster/r.colors.out_sld/r.colors.out_sld.py
Using the generated SLD file with currently released version leads to an ERROR in Geoserver:
```
Error rendering coverage on the fast path
java.lang.UnsupportedOperationException: NaN values can only be set inside a single-point Range
NaN values can only be set inside a single-point Range
```
due to the NULL value line in the sld `<sld:ColorMapEntry color="#ffffff" opacity="0" quantity="NaN"/>`.
To avoid this I added a flag `n` which propagates NULL only if `-n` is set.
=> r.colors.out_sld: do not write NaN in SLD without -n flag

grass7/imagery/i.cutlines/i.cutlines.py
In the moment it is possible that `hnumber_lines` or `hnumber_lines` can get 0. E.g. if `number_lines * (nsrange / ewrange) = 0.815` and then i.cutlines results in an error:
```
...
Finding cutlines in both directions
Traceback (most recent call last): 
File "/usr/local/grass78/scripts/i.cutlines", line 640, in <module>
main()
File "/usr/local/grass78/scripts/i.cutlines", line 310, in main
nsstep = float(region.n - region.s - region.nsres) / hnumber_lines
ZeroDivisionError: float division by zero
Erasing temporary files...
```
To avoid this I added that `hnumber_lines` or `hnumber_lines` must be at least 1.
=> i.cutlines: no 0 vertical or horizontal number of lines

tools/cronjobs_osgeo_lxd/hugo_clean_and_update_job.sh
Optimize deployment steps for speed to minimize risk that users see a
half-deployed server when visiting https://grass.osgeo.org/ during page redeployment (cronjob).
Change: do not remove, then copy into but prepare in a temp directory, then swap directories.
=> hugo deploy script: less downtime

grass7/raster/r.in.nasadem/r.in.nasadem.py
Until now r.in.nasadem was only working in locations with longlat projection. This changes create a temporary location with epsg:4326 and import the nasadem and then reproject it to the target loaction. (It work similar to https://github.com/OSGeo/grass-addons/pull/58)
=> r.in.nasadem: no longlat projection

grass7/raster/r.pops.spread/main.cpp, grass7/raster/r.pops.spread/testsuite/test_r_pops_spread.py
Update to PoPS 1.0.1 release, i.e., the tag v1.0.1 in the ncsu-landscape-dynamics/r.pops.spread repo which in turn uses tag v1.0.0 in PoPS Core (no update needed there).
https://github.com/ncsu-landscape-dynamics/r.pops.spread/releases/tag/v1.0.1
https://github.com/ncsu-landscape-dynamics/pops-core/releases/tag/v1.0.0
Fix parameter handling for kernels:
Code no longer fails without an anthropogenic kernel and natural kernel strength (kappa) is no
longer required when direction is not provided (or none).
Adds test for no anthropogenic kernel and minimalistic command line parameters testing against the current values.
=> r.pops.spread: Update to PoPS version 1.0.1

grass7/raster/r.accumulate/delineate_subwatersheds_recursive.c
Don't repeat:
```c
dir_buf->c[row][col] = id;
done[row][col] = 1;
```
for the current cell.
=> r.accumulate: Do not repeat the same assignments

grass7/raster/r.confusionmatrix/r.confusionmatrix.py
`grass.message` writes the text in `stderr`. The confusion matrix should be printed in `stdout`.
=> r.confusionmatrix: using stdout instead of stderr for matrix

grass7/raster/r.confusionmatrix/r.confusionmatrix.py
`descriptionflag` was not defined in `set_reference()`.
=> r.confusionmatrix: bug fix

grass7/gui/wxpython/wx.stream/gui_modules/rstream_ImageViewer.py, grass7/gui/wxpython/wx.wms/Makefile, grass7/gui/wxpython/wx.wms/ServerInfoAPIs.py, grass7/gui/wxpython/wx.wms/addserver.py, grass7/gui/wxpython/wx.wms/parse.py, grass7/raster/r.connectivity/r.connectivity.corridors/r.connectivity.corridors.py, grass7/vector/v.rast.bufferstats/v.rast.bufferstats.py
Uses the compatibility test from
https://github.com/OSGeo/grass/blob/0a5097cd0e53f3df8285a3bef68b43e8050d273e/lib/python/script/core.py#L37
(and many other places in GRASS-core)
Fixes #274
=> unicode() compatibility fix for Python-2/Python-3 

grass7/imagery/i.sentinel/i.sentinel.mask/i.sentinel.mask.html
I also moved the requirement for BOA input data upwards to make it clear from the beginning that atmospherically corrected S2 images are needed.
=> Remove the string about level 1C in i.sentinel.mask

grass7/raster/r.accumulate/accumulate_iterative.c, grass7/raster/r.accumulate/calculate_lfp_iterative.c, grass7/raster/r.accumulate/delineate_subwatersheds_iterative.c
* Fix segmentation faults when popping up the last item from a stack
* Use direct struct assignments rather than a function for simple copy
=> r.accumulate: Fix segmentation faults

grass7/gui/wxpython/wx.metadata/mdlib/dependency.py
Fix module not found error message.
=> wx.metadata/config: fix module not found error message

grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py, grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py
Fix flake8 error F403: 'from owslib.iso import *' used; unable to detect undefined names
=> PEP8: fix flake8 error F403: 'from owslib.iso import *' used; unable to detect undefined names

grass7/gui/wxpython/wx.metadata/db.csw.admin/db.csw.admin.py, grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py
Fix flake8 error F403: 'from mdlib.cswutil import *' used; unable to detect undefined names
=> PEP8: fix flake8 error F403: 'from mdlib.cswutil import *' used; unable to detect undefined names

grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py
Fix flake8 error F811: redefinition of unused 'CatalogueServiceWeb'
=> PEP8: fix flake8 error F811: redefinition of unused 'CatalogueServiceWeb'

grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
Fix flake8 error F811: redefinition of unused 'RunCommand'
=> PEP8: fix flake8 error F811: redefinition of unused 'RunCommand'

grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py
Fix flake8 error F632: use ==/!= to compare constant literals (str, bytes, int, float, tuple)
=> PEP8: fix flake8 error F632: use ==/!= to compare constant literals (str, bytes, int, float, tuple)

grass7/gui/wxpython/wx.metadata/mdlib/mdgrass.py
**To Reproduce:**
1. Launch `g.gui.metadata`
2. Choose map from tree (bug appear in special cases when backslash continuation character appear in the special position in the map history comments).  I tested on my custom raster map.
My custom raster map history comments:
```
comments="r.proj --quiet location="temp_import_location_21544" mapset="PERMANE\NT" input="dmr" method="nearest" memory=300 resolution=9.99225497862\5072"
```
3. Click on the toolbar pencil icon (Editting)
4. In the right panel hit validate button
```
File "/home/tomas/.grass7/addons/scripts/g.gui.metadata", line 1319, in validate
dispatcher.send(signal='NEW_MD.create')
File "/usr/lib64/grass79/etc/python/grass/pydispatch/dispatcher.py", line 350, in send
**named …
```
=> wx.metadata/mdlib: replace '\' (backslash continuation character) in map history comments

grass7/raster/r.mwprecip/r.mwprecip.py
Fix 'IOError' exception.
http://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/r.mwprecip.log
```
File "C:/Users/landa/grass_packager/grass784RC1/x86_64/addons/r.mwprecip/scripts/r.mwprecip.py", line 275
except IOError as (errno, strerror):
^
SyntaxError: invalid syntax
make: *** [/c/msys64/usr/src/grass784RC1/include/Make/Html.make:14: r.mwprecip.tmp.html] Error 1
rm r.mwprecip.tmp.html
```
=> r.mwprecip: fix 'IOError' exception

grass7/vector/v.in.geopaparazzi/v.in.geopaparazzi.py
Fix compare types, and order py modules.
```
File "/tmp/grass7-tomas-11507/tmpbe23dke7/v.in.geopaparazzi/scripts/v.in.geopaparazzi", line 59, in <module>
from types import DictType, ListType
ImportError: cannot import name 'DictType'
make: *** [/usr/lib64/grass79/include/Make/Html.make:14: v.in.geopaparazzi.tmp.html] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
```
=> v.in.geopaparazzi: fix compare types, and order py modules

grass7/imagery/i.ortho.corr/i.ortho.corr.py
- addresses `ModuleNotFoundError: No module named 'os2emxpath'`
fixes #273
=> i.ortho.corr: replace os2emxpath

grass7/vector/v.class.ml/v.class.ml.py
**Error message**:
```
C:/Users/landa/grass_packager/grass784/x86_64/addons/v.class.ml/scripts/v.class.ml.py:365: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
import imp
VERSION_NUMBER=7.8.4 VERSION_DATE=2020 MODULE_TOPDIR=/c/msys64/usr/src/grass784 \
python3 /usr/src/grass784/dist.x86_64-w64-mingw32/tools/mkhtml.py v.class.ml > /c/Users/landa/grass_packager/grass784/x86_64/addons/v.class.ml/docs/html/v.class.ml.html
File "C:/msys64/usr/src/grass784/dist.x86_64-w64-mingw32/tools/mkhtml.py", line 286, in <module>
tmp_data = read_file(tmp_file)
File "C:/msys64/usr/src/grass784/dist.x86_64-w64-mingw32/tools/mkhtml.py", line 158, in read_file
return decode(s)
File …
```
=> v.class.ml: fix compile module on OS MS Windows platform

grass7/general/g.download.location/g.download.location.html, grass7/general/g.download.location/g.download.location.py
The module can now deal with location being only one of the nested directories for cases
when archiving program creates one extra. It recurses one level into the structure
(can be modified in the code) which adds additional level to what the Python libraries are doing
(which actually makes the code more complex for us).
xz is among the recognized extensions.
Several special cases and error are now handled gracefully with error being reported
for single file in an archive (typically another archive, but leaving that aside)
and for file being incomplete (likely not fully downloaded).
Functions raise an unified exception, main code now calls fatal when that happens.
Filenames without extension don't cause traceback, but cause an error to be reported.
=> g.download.location: Make unzip, untar more robust

tools/cronjobs_osgeo_lxd/check_addons_urls.sh, tools/cronjobs_osgeo_lxd/compile_addons_git.sh, tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh
Allow build Add-Ons with correct src and commits url in the manual page with build script.
Apply first this [PR,](https://github.com/OSGeo/grass/pull/1009) please.
=> tools/cronjobs_osgeo_lxd: fix Add-On src and commits url in the manual html page

tools/cronjobs_osgeo_lxd/check_addons_urls.sh
Explicitly set '/bin/bash' shebang.
```
/home/neteler/cronjobs/check_addons_urls.sh: 30: /home/neteler/cronjobs/check_addons_urls.sh: Syntax error: redirection unexpected
```
=> tools/check_addons_urls.sh: explicitly set '/bin/bash' shebang

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
This PR fixes the following issue in `i.sentinel.download`: 
Using `i.sentinel.download` with `producttype=GRD` or `producttype=SLC` (Sentinel-1 product types) and `footprints=...` fails, because a cloud cover percentage parameter is expected in `save_footprints` which is not available for Sentinel-1 data.
=> i.sentinel.download: enable footprint saving for Sentinel-1 data

grass7/raster/r.learn.ml/r.learn.ml.py
Fixes `DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.`
Ref:
https://github.com/scikit-optimize/scikit-optimize/pull/776
=> r.learn.ml: fix deprecated joblib import

grass7/imagery/i.ann.maskrcnn/i.ann.maskrcnn.detect/i.ann.maskrcnn.detect.py
i.ann.maskrcnn.detect manuals do not build because skimage is not installed on the build server.
Lazy imports should fix it.
Maybe it should be checked for skimage (and PIL?) in a try-except statement?
=> i.ann.maskrcnn.detect: lazy import skimade and PIL

.github/workflows/ci.yml
Update how env vars and path var are set in GitHub Actions after change in the API
(fixes OSGeo/grass#1090).
Use Ubuntu 20.04 (although currently still in preview in GH Actions).
Test more than one Python version. Add version 3.8.
=> ci: Update setting env vars, use Ubuntu 20.04, Python 3.8

grass7/imagery/i.modis/i.modis.download/i.modis.download.py, grass7/imagery/i.modis/i.modis.html, grass7/imagery/i.modis/i.modis.import/i.modis.import.html, grass7/imagery/i.modis/i.modis.import/i.modis.import.py, grass7/imagery/i.modis/libmodis/rmodislib.py
This PR adds support for https://lpdaac.usgs.gov/products/mcd19a2v006/
The input subsets in case of MCD19A2 contain multiple bands. 
Input data:
```
gdalinfo HDF4_EOS:EOS_GRID:"MCD19A2.A2020052.h18v03.006.2020056023047.hdf":grid1km:Optical_Depth_055
...
Band 1 Block=1200x833 Type=Int16, ColorInterp=Gray
Description = AOD at 0.55 micron
Computed Min/Max=0.000,597.000
NoData Value=-28672
Offset: 0,   Scale:0.001
Band 2 Block=1200x833 Type=Int16, ColorInterp=Gray
Description = AOD at 0.55 micron
Computed Min/Max=0.000,575.000
NoData Value=-28672
Offset: 0,   Scale:0.001
Band 3 Block=1200x833 Type=Int16, ColorInterp=Gray
Description = AOD at 0.55 micron
Computed Min/Max=0.000,519.000
NoData Value=-28672
Offset: 0,   Scale:0.001
Band 4 Block=1200x833 Type=Int16, ColorInterp=Gray
Description = …
```
=> i.modis: support for MCD19A2 v006

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
This PR fixes the following Bug in `i.sentinel.coverage`:
The `output` list of scenes may contain scenes that actually do not intersect with the input `bbox`, e.g. because a Sentinel-2 scene only covers the southeast bit of its UTM-tile. This bug only occurs if the remaining scene/s do cover the entire `bbox`.
=> i.sentinel.coverage: fix potentially wrong output scene list

grass7/raster/r.subdayprecip.design/r.subdayprecip.design.py
This PR fixes `r.subdayprecip.design` which currently fails with
```
ERROR: Column <area_25> exists. To overwrite, use the --overwrite flag
```
=> r.subdayprecip.design: no need to call v.db.addcolumn before v.to.db

grass7/raster/r.learn.ml2/r.learn.predict/r.learn.predict.py, grass7/raster/r.learn.ml2/r.learn.train/r.learn.train.py, grass7/raster/r.learn.ml2/rlearnlib/Makefile, grass7/raster/r.learn.ml2/rlearnlib/raster.py, grass7/raster/r.learn.ml2/rlearnlib/transformers.py
```
File "/tmp/.grass7//scripts/r.learn.train", line 362, in <module>
from raster import RasterStack
File "/tmp/.grass7/etc/r.learn.ml2/raster.py", line 21, in <module>
from transformers import CategoryEncoder
File "/tmp/.grass7/etc/r.learn.ml2/transformers.py", line 1, in <module>
from sklearn.base import BaseEstimator, TransformerMixin
ModuleNotFoundError: No module named 'sklearn'
```
Plus fix import modules from 'rlearnlib' lib and install this lib dir content in the 'addons/etc/r.learn.ml2/rlearnlib' dir.
=> r.learn.ml2: fix lazy import of 'sklearn' module

tools/cronjobs_osgeo_lxd/check_addons_urls.sh, tools/cronjobs_osgeo_lxd/cron_job_list_grass
Fixes #359. Color output is off by default (script run as cron job). It can be turned on via a script parameter (if you run script locally).
=> tools/check_addons_urls: add parameter for optional color text output

grass7/vector/v.in.redlist/v.in.redlist.py
```
File "C:/Users/landa/grass_packager/grass784/x86_64/addons/v.in.redlist/scripts/v.in.redlist.py", line 66, in <module>
from osgeo import ogr
ModuleNotFoundError: No module named 'osgeo'
```
Log file:
https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/v.in.redlist.log
=> v.in.redlist: lazy import of 'osgeo' module

grass7/vector/v.in.pygbif/v.in.pygbif.py
```
File "C:/Users/landa/grass_packager/grass784/x86_64/addons/v.in.pygbif/scripts/v.in.pygbif.py", line 185, in <module>
from osgeo import ogr, osr
ModuleNotFoundError: No module named 'osgeo'
```
Log file:
https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/v.in.pygbif.log
=> v.in.pygbif: lazy import of 'osgeo' module

grass7/raster/r.object.activelearning/r.object.activelearning.py
```
File "/tmp/.grass7//scripts/r.object.activelearning", line 105, in <module>
import scipy
ModuleNotFoundError: No module named 'scipy'
```
=> r.object.activelearning: fix lazy import of 'scipy', 'numpy' module

grass7/imagery/i.ann.maskrcnn/i.ann.maskrcnn.html
The installation command in docs expected the installation from local path. As the modules are part of the official AddOns repository, the path specification in the installation command is not needed anymore.
=> i.ann.maskrcnn: update installation command in docs

grass7/raster/r.out.kde/r.out.kde.py
Fixes error (see: https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/r.out.kde.log)
```
File "C:/Users/landa/grass_packager/grass784/x86_64/addons/r.out.kde/scripts/r.out.kde.py", line 51, in <module>
from PIL import Image
ModuleNotFoundError: No module named 'PIL'
make: *** [/c/msys64/usr/src/grass784/include/Make/Html.make:14: r.out.kde.tmp.html] Error 1
```
=> r.out.kde: lazy import of PIL library

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html, grass7/imagery/i.landsat/i.landsat.html, grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.html, grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py
This PR  addresses issue https://github.com/veroandreo/i.landsat/issues/15. The implemented option is a much simpler version of the function available in `i.sentinel.import`, i.e., it just parses the filenames of files to be imported and gets date, satellite number (5, 7 or 8) and band info to create the register file.
=> i.landsat.import: add register_output option

grass7/gui/wxpython/wx.mwprecip/mw3.py, grass7/gui/wxpython/wx.mwprecip/pgwrapper.py
```
File "/home/neteler/.grass7/addons/scripts/g.gui.mwprecip", line 27, in <module>
from mw3            import *
File "/home/neteler/.grass7/addons/etc/g.gui.mwprecip/mw3.py", line 8, in <module>
import psycopg2
ModuleNotFoundError: No module named 'psycopg2'
```
=> wxGUI/wx.mwprecip: fix lazy import of 'psycopg2', 'numpy' module 

grass7/vector/v.in.pygbif/v.in.pygbif.py
**Error message** (during compilation on the server)**:**
```
ERROR: Unable to load GDAL Python bindings (requires package 'python-gdal'
or Python library GDAL to be installed).
```
[Compilation log file](https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/v.in.pygbif.log).
We need to move 'osgeo' module import into main() function body. Same as with the [g.proj.identify](https://github.com/OSGeo/grass-addons/blob/master/grass7/general/g.proj.identify/g.proj.identify.py#L145) add-on, which was compiled successfully.
=> v.in.pygbif: fix lazy import of 'osgeo' module

grass7/raster/r.out.kde/r.out.kde.py
**Error message** (during compilation on the server)**:**
```
ERROR: Cannot import PIL. Please install the Python pillow package.
```
[Compilation log file](https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/r.out.kde.log).
We need to move 'PIL' module import into main() function body. Same as with the [g.proj.identify](https://github.com/OSGeo/grass-addons/blob/master/grass7/general/g.proj.identify/g.proj.identify.py#L145) add-on, which was compiled successfully.
=> r.out.kde: fix lazy import of 'PIL' module

grass7/vector/v.in.redlist/v.in.redlist.py
**Error message** (during compilation on the server)**:**
```
ERROR: Unable to load GDAL Python bindings (requires package 'python-gdal'
or Python library GDAL to be installed).
```
[Compilation log file](https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/v.in.redlist.log).
We need to move 'osgeo' module import into main() function body. Same as with the [g.proj.identify](https://github.com/OSGeo/grass-addons/blob/master/grass7/general/g.proj.identify/g.proj.identify.py#L145) add-on, which was compiled successfully.
=> v.in.redlist: fix lazy import of 'osgeo' module

grass7/vector/v.vect.stats.multi/v.vect.stats.multi.html
This improves documentation (typos, parameter order) and adds new example with custom column list
and output names.
=> v.vect.stats.multi: Add example with column names

grass7/gui/wxpython/wx.metadata/Makefile
Adress #397
The Makefile for mdlib might have to be checked as well...
When I tried to install with the make command given by
```g.extension -d extension=wx.metadata operation=add```
I get plenty of errors (but also the make command g.extension spits out might be incorrect...
=> wx.metadata: check dependencies with Python3

grass7/gui/wxpython/wx.metadata/mdlib/globalvar.py
Add missing 'globalvar' py script file. 
```
File "/home/neteler/.grass7/addons/scripts/db.csw.harvest", line 57, in <module>
from mdlib import globalvar
ImportError: cannot import name 'globalvar' from 'mdlib' (/home/neteler/src/grass-addons/grass7/gui/wxpython/wx.metadata/mdlib/__init__.py)
```
Compilation [log file](https://grass.osgeo.org/addons/grass7/logs/wx.metadata.log).
=> wxGUI/wx.metadata: add missing 'globalvar' py script file

grass7/imagery/i.modis/i.modis.import/i.modis.import.py
When running `i.modis.import` the command can end up with misleading error message
```
ERROR: pymodis library is not installed
```
even the pyMODIS library is installed.
This PR helps to understand user why pyMODIS library loading failed:
```
ERROR: Unable to import pymodis library: Python slugify library not found,
please install unicode-slugify for Python > 3 or slugify for Python
< 3
```
=> i.modis.import: misleading error message (pymodis is not installed)

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.py
I tried using `excludes` because the description says "if the first option is given, none of the subsequent options may be given", but it does not work as expected. Therefore, I set 2 exclusive rules: -l cannot be used with id nor with output; -l is only for listing scenes found.
=> fix rules: -l should not be used when id or output is given

grass7/raster/r.modis/Makefile, grass7/raster/r.seasons/r.seasons.html, grass7/raster/r.sentinel/Makefile
Deleting empty directories:
- raster/r.modis/ (nowadays called `i.modis`)
- raster/r.sentinel/ (nowadays called `i.sentinel`)
Fix outdated names in `r.seasons` manual.
Completes #375
=> Remove empty addon directories: r.modis and r.sentinel

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.py
In the latest release of [landsatxplore](https://github.com/yannforget/landsatxplore) the `bbox` parameter was adapted to be consistent with the documentation (xmin, ymin, xmax, ymax). See also https://github.com/yannforget/landsatxplore/pull/30/files.
This PR swaps the respective parts of `i.landsat.download` to be consistent with this update.
=> i.landsat.download: swap lon/lat order due to landsatxplore update

grass7/raster/r.extract/Makefile, grass7/raster/r.extract/r.extract.html, grass7/raster/r.extract/r.extract.py, grass7/raster/r.extract/testsuite/r_extract_test.py
This is a wrapper around r.reclass to simplify extraction of categories in integer raster maps:
```
r.extract input=zipcodes output=selected_zipcodes cats=27605,27601 -c
```
=> r.extract: new addon for extracting categories 

grass7/raster/r.in.usgs/r.in.usgs.py
USGS changed the base API URL.
dataset_name was unused, but the new USGS JSON has datasets as an empty list,
so the [0] access was failing. Removing dataset_name code.
=> r.in.usgs: Update USGS URL, remove unused var

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
This PR fixes two issues with `i.sentinel.coverage`:
1. Downloading a lot of footprints together using `i.sentinel.download `may yield incorrect individual footprints. This is avoided by downloading all identified footprints individually (see attached screenshots)
2. Using `v.patch` to patch all footprints together yields a "XOR" result: overlapping areas are missing. This is avoided by using `v.overlay` sequentially
This PR further 
- Adds rules for input options
- Removes check for `i.sentinel` installation
- corrects some minor linting issues
Developed together with @anikaweinmann
=> i.sentinel.coverage: fix footprints

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
Instead of no output print the module now prints the result into the terminal when no output file was defined.
=> i.sentinel.coverage: print result when no output defined

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
To fix #432 this MR reads also the Error message of `i.sentinel.downlad` and write them in an error message. Also the python trace of #431 is removed by this.
Additionally by the footprint merge all not needed columns are removed, cause otherwise by many Sentinel scenes an error appear by dropping the `b_identifier` column.
=> i.sentinel.coverage: parse error msg of i.sentinel.download

grass7/raster/r.slope.direction/r.slope.direction.html
Thanks for catching the flaw in the manual. I simply forgot to update the manual after major module change.
This PR should fix #433
Any checking of clarity, spelling and grammar would be very much appreciated...
=> r.slope.direction: replace method with slope_measure in the manual

grass7/raster/r.learn.ml2/r.learn.train/r.learn.train.py
By using `scikit-learn==0.24.0` `r.learn.train -f group=in_group model_name=RandomForestClassifier n_jobs=3 cv=5 training_points=training_set field=class_num save_model=model.gz` leads to an error:
```
Removing samples with NaN values in the raster feature variables...
File "/usr/local/grass78/scripts/r.learn.train", line 872, in <module>
main()
File "/usr/local/grass78/scripts/r.learn.train", line 641, in main
outer = StratifiedKFold(n_splits=cv, random_state=random_state)
File "/usr/lib/python3.8/site-packages/sklearn/utils/validation.py", line 63, in inner_f
return f(*args, **kwargs) 
File "/usr/lib/python3.8/site-packages/sklearn/model_selection/_split.py", line 636, in __init__
super().__init__(n_splits=n_splits, shuffle=shuffle,
File …
```
=> r.learn.train: fix for scikit-learn==0.24.0

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.py, grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py
Here's a first working version of `i.landsat.download` with support for collection 2 data conforming with the new landsatxplore.
There have been some changes in terms of metadata in Landsat collections. Hence, instead of `acquisitionDate`, I have (for now) used `publishDate`. This has a problem though. While it has info for collection 1, it appears as `Unknown` for L8 in collection 2 only. Hence preventing the sort these data by date.
The option would be to use `scene['temporalCoverage']['startDate']` that is populated properly in both collection 1 and 2, but my limited python knowledge *prevents* me from modifying current lines 233-242 where date and clouds are used to sort the listed scenes. Can someone help here, please?? :pray: 
Here's my hardcoded testing script:
```
#!/usr/bin/env …
```
=> WIP: add collection 2 support in i.landsat.download

tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh, tools/cronjobs_osgeo_lxd/cron_grass7_HEAD_build_bins.sh
A DuckDuckGo based manual site search field is injected during compilation.
See "at work" at bottom of
https://grass.osgeo.org/grass78/manuals/index.html
Rationale: unless we don't change the manual pages to e.g. Sphinx, or install an own search engine, through this way we have at least a search form.
=> cronjobs: manual search form added

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.html, grass7/imagery/i.landsat/i.landsat.html, grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.html
This PR fixes i.landsat.download examples, adds a short explanation about new `timeout` option and includes the new `i.landsat.qa` + author to the main i.landsat manual. Shall we add further examples?
=> i.landsat manuals: add timeout option in i.landsat.download and add i.landsat.qa + author

grass7/raster/r.pi/r.pi.enn/matrix.c, grass7/raster/r.pi/r.pi.fnn/heap.c, grass7/raster/r.pi/r.pi.fnn/matrix.c
fixes #438
Remarks
- all related error messages in `r.pi.*` should be standardized in a separate PR
- or, better: remove entirely since `Rast_open_new()` in GRASS-core doesn't have any following `G_fatal_error()` error messages as not needed? Maybe an old artifact of G6 times...
=> r.pi.enn + r.pi.fnn: fix error message

grass7/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py, grass7/gui/wxpython/wx.metadata/mdlib/cswlib.py, grass7/gui/wxpython/wx.metadata/mdlib/mdeditorfactory.py, grass7/gui/wxpython/wx.metadata/mdlib/mdjinjaparser.py
Fix lazy import of GRASS GIS wxPy `core.gcmd` module classes during compilation on Windows platform (server where builds Add-Ons)
**Error message**
```
File "C:/Users/landa/grass_packager/grass785/x86_64/addons/wx.metadata/scripts/g.gui.cswbrowser.py", line 26, in <module>
from mdlib.cswlib import CSWBrowserPanel, CSWConnectionPanel
File "C:\msys64\usr\src\grass-addons\grass7\gui\wxpython\wx.metadata\mdlib\cswlib.py", line 30, in <module>
from core.gcmd import GError, GMessage, GWarning
File "C:/msys64/usr/src/grass785/dist.x86_64-w64-mingw32\gui\wxpython\core\gcmd.py", line 43, in <module>
from win32file import ReadFile, WriteFile
ModuleNotFoundError: No module named 'win32file'
```
Full [compilation log …
=> wxGUI/wx.metadata: fix lazy import of GRASS GIS wxPy 'core.gcmd' module classes

grass7/imagery/i.edge/canny.c, grass7/imagery/i.edge/main.c
`i.edge` currently exits with fatal error if the input is empty. The new -n flag allows to create an empty output map without fatal error if the input map is empty.
=> i.edge: add -n flag for empty input/output

grass7/imagery/i.landsat/i.landsat.download/i.landsat.download.py
The library landsatxplore has changed to more consistent field names and types (see https://github.com/yannforget/landsatxplore/commit/da151b6128ffed9d4be2646ea8d92e0f245e9c8b). 
This PR adapts i.landsat.download to such field name and type changes. Also, the `acquisition_date` now reports a proper date that can be directly sorted, so I reverted the last workaround with `temporalCoverage` and dictionary re-indexing. 
This is hopefully the last update for a while.
=> i.landsat.download: update to landsatxplore v0.13.0

.github/workflows/ci.yml
Avoid two same names in the list of jobs in the main build and test workflow.
=> CI: Add Python version to job name

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
This PR adapts the handling of scene names to be able to correctly identify Sentinel-1 SLC data. See also #447. SLC file names have one more `_` (underscore) which messed with the identification of scene specifications by `' '.split('_')`
=> i.sentinel.coverage: adapt scenename handling for SLC data

grass7/raster/r.forestfrag/r.forestfrag.py, grass7/raster3d/r3.forestfrag/r3.forestfrag.py
This does for r3.forestfrag what 44ebd8fc4d1f541143d3a2507a056c521eebf2ec does for r.forestfrag.
Unused imports are removed also from r.forestfrag.
Removes unused flag -s (show r.report output) is from r3.forestfrag.
Fixes #465.
=> r3.forestfrag: Make string replace Python 3 compatible

grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py
This PR partially reverts #420. 
It keeps tarfile instead of shutil, but removes the use of `/vsitar/` driver because it is extremely slow for reading files (to import 2 L8 scenes took more than 10 minutes). It didn't appear so slow when I first tested for #420. 
We could set the reading cache to a larger amount, but in any case, users of level 1 data would still need to uncompress the .tar.gz files to get the metadata file for `i.landsat.toar`. So, for now, I preferred to go back to uncompress from the beginning.
Any other suggestion is more than welcome! :)
=> i.landsat.import: partially revert #420

grass7/imagery/i.landsat/i.landsat.import/i.landsat.import.py
Given that some artifacts appear especially when importing L7 with SLC stripping problem when using bilinear as resample method, this PR adds the option resample so users can select a preferred method according to their needs. Default answer is nearest as in r.import.
=> i.landsat.import: add resample option so user can select resample method

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html, grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
`i.sentinel.download` uses the URL `https://scihub.copernicus.eu/dhus` as standard URL for the `sentinelsat` API to request from ESA-Copernicus Open Access Hub. `sentinelsat`'s default option seems to have changed at some point to `https://scihub.copernicus.eu/apihub` (https://sentinelsat.readthedocs.io/en/latest/api_reference.html) and also the main page of the Copernicus Open Access Hub (https://scihub.copernicus.eu/) encourages to use this URL: `Access to APIs (no GUI)
All users downloading data on a regular basis are encouraged to use this access point for a better performance`.
This PR thus changes the default `api_url` of `i.sentinel.download` to `https://scihub.copernicus.eu/apihub`. All downloading/query tests so far were successful also with the new url.
If there is a strong …
=> i.sentinel.download: change ESA api_url to https://scihub.copernicus.eu/apihub

.github/workflows/test.sh
Moved (due to server failure) from
- http://fatra.cnr.ncsu.edu/data/nc_spm_full_v2alpha2.tar.gz
to
- https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz
in order to get the CI running again.
See also https://github.com/OSGeo/grass/pull/1463
=> NC full sample dataset: new URL

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
This PR fixes three bugs when using `i.sentinel.download` to download from USGS using an **ESA-identifier**:
- Automatic tile association needs the tile in the format `32UMB`, i.e. without a `T` at the beginning. Simply replacing `T` with `''` leads an error when a `T` is also in the tile definition (e.g. `31UFT`)
- Automatic filenaming checking failed for some scenes because of a bug in the regular expression
- For some scene-identifiers from ESA-Hub there are **two** scenes in USGS (see screenshot below). This redundancy is solved by using ESA's `<Product_Discriminator>` (The last part of each S2-filename, see https://sentinel.esa.int/web/sentinel/user-guides/sentinel-2-msi/naming-convention/)
=> i.sentinel.download: fixes for downloading using ESA-identifier

grass7/imagery/i.sentinel/i.sentinel.coverage/i.sentinel.coverage.py
This PR fixes #482: When using `i.sentinel.coverage` and no products are found, `i.sentinel.coverage` now exits with `No products found`.
=> i.sentinel.coverage: Exit with correct message if no products are found

.github/workflows/ci.yml
Make the HTML test report available as an GitHub Actions artifact.
One ZIP file for each run for download, available for 3 days.
Port of OSGeo/grass#1290.
=> CI: Make test report available as artifact

grass7/raster/r.in.nasadem/r.in.nasadem.py, grass7/raster/r.in.srtm.region/r.in.srtm.region.py
Due to https://github.com/OSGeo/grass/pull/1240 the output structure of `g.proj -g` has changed, leading to `KeyError: 'EPSG'`:
```
r.in.nasadem user='neteler' password='XXXXXXXXX' output=nasadem resolution=30
File "/home/mundialis/.grass7/addons/scripts/r.in.nasadem", line 631, in <module>
main()
File "/home/mundialis/.grass7/addons/scripts/r.in.nasadem", line 475, in main
SRCGISRC, TMPLOC = createTMPlocation()
File "/home/mundialis/.grass7/addons/scripts/r.in.nasadem", line 342, in createTMPlocation
if grass.parse_command('g.proj', flags='g')['EPSG'] != str(epsg):
KeyError: 'EPSG'
ERROR: Region <r_in_nasadem_region_409609> not found
Error in atexit._run_exitfuncs:
File …
```
=> r.in.nasadem + r.in.srtm.region: fix PROJ parsing

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.html, grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py, grass7/imagery/i.sentinel/i.sentinel.parallel.download/i.sentinel.parallel.download.py
While Querying Sentinel-2 data from Google Cloud (https://cloud.google.com/storage/docs/public-datasets/sentinel-2) requires a google account and a GCP project (not free), the Sentinel-2 data themselves are freely available. They can be accessed by following the folder structure. Although it is not possible to download an entire .SAFE-folder, all individual files can be downloaded and put together to a complete S2-scene.
This PR enables `i.sentinel.download` to download from GCS. Searching and filtering scenes still requires an ESA-login.
=> i.sentinel.download: Enable downloading from Google Cloud

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
The API Hub URL to download Sentinel-data from the Copernicus Open Access Hub has changed from https://scihub.copernicus.eu/apihub/ to https://apihub.copernicus.eu/apihub/ as of 28 April 2021. See also [announcement 1](https://scihub.copernicus.eu/news/News00865) and [announcement 2](https://scihub.copernicus.eu/news/News00865). Even though "the old URL will not be dismissed" ([announcement 1](https://scihub.copernicus.eu/news/News00865)) trying to list and download Sentinel data using the old URL yields an authentication error. Hence, this PR adapts the default URL. 
With the adapted URL searching for data with the `-l` flag and downloading footprints works again. However, data download was so far **not successful** as all requested datasets supposedly lie in the long-term archive (even …
=> i.sentinel.download: adapt API URL

README.md
* delete trailing spaces
* set line length to 80 characters
* delete multiple spaces after hashes in titles
* delete trailing punctuation in titles
* avoid bare URLs
* use code block style for code blocks
* delete them peculiar spaces appearing at the beginning of some lines
=> README.md: Markdown standardization

grass7/display/d.vect.thematic2/d.vect.thematic2.py, grass7/hadoop/hd/hdfsgrass/grass_map.py, grass7/raster/r.catchment/r.catchment.py, grass7/raster/r.mcda.output/r.mcda.output.py, grass7/raster/r.mcda.roughset/r.mcda.roughset.py, grass7/vector/v.explode/v.explode.py, grass7/vector/v.gsflow.export/v.gsflow.export.py, grass7/vector/v.in.gns/v.in.gns.py, grass7/vector/v.in.wfs2/wfs_base.py, grass7/vector/v.what.spoly/v.what.spoly.py
Following #515 I located some more uses of `file()` to open files among grass7 addons. `file()` was removed with Python 3 and leads to fatal error. This replaces those remaining cases with `open()`.
=> Use open() for opening files, Python 3 update

grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
Fixes broken manual page creation on GRASS GIS server:
```
File "/home/neteler/.grass7/addons/scripts/i.sentinel.download", line 171, in <module>
from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'
make[1]: *** [/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu//include/Make/Html.make:14: i.sentinel.download.tmp.html] Error 1
```
=> i.sentinel.download: try/except tqdm import

grass7/raster/r.green/r.green.biomassfor/Makefile, grass7/raster/r.green/r.green.biomassfor/r.green.biomassfor.html, grass7/raster/r.green/r.green.gshp/Makefile, grass7/raster/r.green/r.green.gshp/r.green.gshp.html, grass7/raster/r.green/r.green.html, grass7/raster/r.green/r.green.hydro/Makefile, grass7/raster/r.green/r.green.hydro/libhydro/plant.py, grass7/raster/r.green/r.green.hydro/r.green.hydro.html, grass7/raster/r.green/r.green.hydro/r.green.hydro.technical/r.green.hydro.technical.py, grass7/raster/r.green/r.green.install/r.green.install.html
- Makefile: added missing rule to install meta manual pages
- manual: fix headers of meta manual pages
- manual: minor HTML fixes
- manual: fix headers of meta manual pages
- Python: Attempt to fix `IndentationError: expected an indented block`
Addresses https://github.com/OSGeo/grass/issues/1499
TODO (help wanted):
`r.green.install:35: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses`
=> r.green: Python, Makefile and manual fixes 

grass7/raster/r.vol.dem/chull.c
Backport of v.hull related changes (https://github.com/OSGeo/grass/pull/1567) to fix compilation error:
```
gcc  -Werror-implicit-function-declaration -fno-common   -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include    -DPACKAGE=\""grassmods"\"   -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include -I/home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include -DRELDIR=\"/home/neteler/src/grass-addons/grass7/raster/r.vol.dem\" -o OBJ.x86_64-pc-linux-gnu/chull.o -c chull.c
In file included from /home/neteler/src/releasebranch_7_8/dist.x86_64-pc-linux-gnu/include/grass/gis.h:26,
from chull.c:26:
chull.c:32:19: error: expected ‘;’, identifier or ‘(’ before ‘_Bool’
{ BFALSE, …
```
=> r.vol.dem: fix Boolean types

.github/workflows/ci.yml
Only create link if versionless startup script `grass` not yet present (GRASS GIS < 8)
=> CI: fix link creation for GRASS GIS 8

grass7/imagery/i.modis/i.modis.download/i.modis.download.html, grass7/imagery/i.modis/i.modis.download/i.modis.download.py, grass7/imagery/i.modis/i.modis.html, grass7/imagery/i.modis/i.modis.import/i.modis.import.html
- catch more (user) errors
- more messages improved
- user example added with .netrc file
- fix broken URL to i.modis.qc
- remove obsolete GRASS GIS version test (hence, it also works with GRASS GIS 8)
=> i.modis.download: more reasonable error handling

grass7/general/g.projpicker/g.projpicker.py
Really minor, but potentially very helpful as long as projpicker is not a part of core repository.
=> g.projpicker: Add error message if projpicker not found on system.

grass7/general/g.projpicker/g.projpicker.py
Personally, I think this `black` formatting breaks *my* semantic indentation and even violates [PEP 8](https://www.python.org/dev/peps/pep-0008/). Also, it's not compatible with vim's `gq` and `gw` with the default line width. https://lists.osgeo.org/pipermail/grass-dev/2021-June/095226.html
=> Reapply black without any options

grass7/general/g.isis3mt/g.isis3mt.py, grass7/imagery/i.ann.maskrcnn/i.ann.maskrcnn.detect/i.ann.maskrcnn.detect.py, grass7/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py, grass7/raster/r.connectivity/r.connectivity.distance/r.connectivity.distance.py, grass7/raster/r.flowfill/r.flowfill.py, grass7/raster/r.learn.ml2/r.learn.train/r.learn.train.py
I changed several addons in order to make manual pages compile.
See compilation log here:
https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/
Addons containing serval modules can have failed even though the log says differently... Would be great if you could check the addon you contributed to...
=> Fix compilation of addon manuals for Windows

src/general/g.projpicker/g.projpicker.html
XOR on two geometries at a time means feeding more than two geometries does not return mutually exclusive projections.
=> g.projpicker: More information about XOR

src/general/g.download.location/g.download.location.py
This adds path option for compatibility with the version of the module in v8.
It is an additional option, so the original dbase still works.
Same code can now be used for v7 and v8, but the original code for v7 still works
(v8 code should be updated to use the version in core, not the addon).
=> g.download.location: Add path option for compatibility with core module

.github/workflows/test.sh
- g.download.location is included in the core for v8, so install it only if missing (assuming v7).
- Use path instead of dbase as in the core version of g.download.location (addons version supports both).
=> CI: Install g.download.location only if needed

CONTRIBUTING.md
* The default (and thus usually the correct base branch) is grass7, not master.
* Some items related to remotes and merging were updated or corrected.
* Some parts were specialized to addons (original text is from core).
=> Update contributing file to master to grass7 switch

.github/workflows/ci.yml, tools/cronjobs_osgeo_lxd/README.md, tools/cronjobs_osgeo_lxd/cron_grass74_releasebranch_74_build_bins.sh, tools/cronjobs_osgeo_lxd/cron_grass74_src_relbr74_snapshot.sh, tools/cronjobs_osgeo_lxd/cron_grass76_releasebranch_76_build_bins.sh, tools/cronjobs_osgeo_lxd/cron_grass76_src_relbr76_snapshot.sh, tools/cronjobs_osgeo_lxd/cron_grass78_releasebranch_78_build_bins.sh, tools/cronjobs_osgeo_lxd/cron_grass78_src_relbr78_snapshot.sh, tools/cronjobs_osgeo_lxd/cron_grass8_HEAD_build_bins.sh, tools/cronjobs_osgeo_lxd/cron_grass8_HEAD_src_snapshot.sh
The development/default branch in the core repo will be renamed from master to main.
This includes updates of the CI, comments and documentation.
It removes the mention of the master/main branch when not necessary.
Notably, this does not update the code for OSGeo cron jobs because name of branch is used there additionally as a directory name and it is part of some non-scripted part of the setup.
This needs to be changed together with the setup on the OSGeo server.
=> Update name of core branch from master to main

src/raster/r.colors.out_sld/r.colors.out_sld.html
=> r.colors.out_sld: fix typo in description

src/imagery/i.landsat/i.landsat.download/i.landsat.download.py
This PR adds an optional `limit` options to `i.landsat.download` (similar to `i.sentinel.download`, https://github.com/OSGeo/grass-addons/blob/grass7/src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py#L88) to limit the maximum number of scenes to be listed/downloaded.
=> i.landsat.download: add limit option

src/gui/wxpython/wx.metadata/g.gui.metadata/g.gui.metadata.py, src/gui/wxpython/wx.metadata/mdlib/cswlib.py
Fix lazy import of GRASS GIS wxPy 'core.gcmd', 'gui_core.forms' module classes .Fix compilation errors on the OS MS Windows.
**Error messages**
```
File "C:/Users/landa/grass_packager/grass786RC2/x86_64/addons/wx.metadata/scripts/g.gui.cswbrowser.py", line 26, in <module>
from mdlib.cswlib import CSWBrowserPanel, CSWConnectionPanel
File "C:\msys64\usr\src\grass-addons\src\gui\wxpython\wx.metadata\mdlib\cswlib.py", line 30, in <module>
from gui_core.forms import GUI
File "C:/msys64/usr/src/grass786RC2/dist.x86_64-w64-mingw32\gui\wxpython\gui_core\forms.py", line 98, in <module>
from gui_core.widgets import StaticWrapText, ScrolledPanel, ColorTablesComboBox, \
File "C:/msys64/usr/src/grass786RC2/dist.x86_64-w64-mingw32\gui\wxpython\gui_core\widgets.py", …
```
=> wxGUI/wx.metadata: fix lazy import of GRASS GIS wxPy 'core.gcmd', 'gui_core.forms' module classes

src/vector/v.greedycolors/main.c
Neighboring areas should in theory not have the same category value, such areas should be dissolved. However, this can happen and is accounted for by this PR.
=> v.greedycolors: fix if neighboring areas have the same cat

src/raster/r.in.usgs/r.in.usgs.py
* Split assigneded memory between parallel subprocesses based on nprocs instead of passing the memory value as is.
* Keep extracted file in cache by default. -k now only adds keeping of tiles in the target mapset. Message about -k enable was removed.
=> r.in.usgs: Split memory amount, keep extracted files

src/raster/r.in.usgs/r.in.usgs.html, src/raster/r.in.usgs/r.in.usgs.py
Instead of a required output/work/cache dir, use a subdirectory of the user cache dir according to the standards of each operating system.
Linux/Freedesktop uses .cache and we use grass as the application name, then version string (from g.version), and then name of the module.
MacOS is the same, but in Library/Caches. For Windows, we use APPDATA as in the startup script with Cache as an additional subdirectory.
=> r.in.usgs: Use system user cache dir

src/vector/v.mapcalc/Makefile, src/vector/v.stream.profiler/Makefile
fix `MODULE_TOPDIR = ...garbage` entries to `MODULE_TOPDIR = ../..`
=> v.mapcalc, v.stream.profiler: fix MODULE_TOPDIR

.github/workflows/ci.yml
* Instead of v7.8, test with v8.0 release branch in the grass8 branch.
* Add test with Python 3.10.
* Remove test with Python 3.6.
* Keep testing only every second version to reduce jobs - add a comment about that.
* Use (explicit) strings to specify versions (not floats).
=> CI: Test with v8.0 in grass8 branch

src/raster/r.learn.ml/r.learn.ml.py
Sci-kit learn updated Jaccard score output metric to be named "jaccard_score."
=> r.learn.ml: renamed jaccard_similarity_score to jaccard_score

src/raster/r.area.createweight/r.area.createweight.html, src/raster/r.area.createweight/r.area.createweight.py, src/vector/v.area.weigh/v.area.weigh.html
As a first attempt to address https://lists.osgeo.org/pipermail/grass-user/2021-December/082767.html:
- r.area.createweight manual:
- clarify installation of dependencies
- fix addon links
- crosslink this addon in v.area.weigh manual
TODO: suggestions welcome for MacOS and Pandas dependency.
=> r.area.createweight manual: clarify installation of dependencies

src/imagery/i.sentinel/i.sentinel.download/i.sentinel.download.py
By trying to download the footprints, I got the follow error:
```
Generating WKT from AOI map (5 vertices)...
Sending WKT from AOI map to ESA...
36 Sentinel product(s) found
Writing footprints into <fp>...
- 'VirtualXPath'	[XML Path Language - XPath]
File "/home/mundialis/.grass8/addons/scripts/i.sentinel.download", line 1262, in <module>
sys.exit(main())
File "/home/mundialis/.grass8/addons/scripts/i.sentinel.download", line 1217, in main
downloader.save_footprints(options["footprints"])
File "/home/mundialis/.grass8/addons/scripts/i.sentinel.download", line 889, in save_footprints
if not any(type in prod_types for type in cloudcover_products):
NameError: name 'cloudcover_products' is not defined
```
This change is fixing this error.
=> i.sentinel.download: fix footprints

.github/workflows/ci.yml
* Replace full matrix with all combinations of Python version and GRASS version by hand-picked combinations.
* Replace Python 3.10 by 3.9 because of failing GDAL package install.
In the future, tags or other branches can be added more freely without introducing multiple new jobs.
New Python versions can be tested with recent GRASS versions without interfering with old GRASS versions.
Multiple Python versions can still be tested (with a reduced number of jobs), although not in combination
with all GRASS versions.
=> Reduce build matrix, remove Python 3.10

utils/cronjobs_osgeo_lxd/README.md, utils/cronjobs_osgeo_lxd/compile_addons_git.sh, utils/cronjobs_osgeo_lxd/cron_job_list_grass, utils/cronjobs_osgeo_lxd/get_page_description.py, utils/cronjobs_osgeo_lxd/grass-addons-fetch-xml.sh
**UNUSED SCRIPTS**
Nonetheless,
- partial update to scripts in `grass7` branch
- renaming of build scripts to more standardized names (see https://github.com/OSGeo/grass-addons/pull/613#issuecomment-991960892)
- update cron_job_list_grass accordingly. Note that this crontab is **NOT USED**. Instead, the version in the `grass8` branch is active.
(relates to #651 - grass8)
=> Cleanup of older GRASS GIS 7 addons cronjobs on grass.osgeo.org

utils/cronjobs_osgeo_lxd/grass-addons-index.sh
This link does not exists on server:
https://wingrass.fsv.cvut.cz/grass80/x86_64/addons/latest/logs/
changed to
https://wingrass.fsv.cvut.cz/grass80/x86_64/addons/grass-8.0.dev/logs/
=> addons: fix winGRASS log files URL

utils/cronjobs_osgeo_lxd/README.md, utils/cronjobs_osgeo_lxd/build-xml.py, utils/cronjobs_osgeo_lxd/compile_addons_git.sh, utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
Generate addons modules.xml file on osgeo lxd container server. Requires this [PR ](https://github.com/OSGeo/grass/pull/2054) to be applied before. 
Note:
build-xml.py script I took over from this [PR](https://github.com/OSGeo/grass-addons/pull/220) with small modification.
=> utils/cronjobs_osgeo_lxd: generate addons modules.xml file on osgeo lxd container server

src/raster/r.convergence/main.c, src/raster/r.convergence/r.convergence.html
Since the changes are bigger than only simple spelling fixes for this addon, I created a pull request to discuss the changes made in the description of the slope flag, and with the figure. Some HTML elements were also invalid, so I closed the tags to have a valid file. I changed some characters containing umlauts with HTML entities since while the file is UTF-8, the deployed webpage has charset iso-8859-1, making these characters appear as Mojibake.
The original sentence was hard to understand, even by me and studying the code, so I'd like a little feedback to let me know if it still has the same meaning, or if the new wording is more appropriate now.
=> Linguistic revision in r.convergence

src/raster/r.connectivity/r.connectivity.corridors/r.connectivity.corridors.py
Uses a default value for ulimit to use when module resource cannot be imported. The resource module is available for Linux, but not Windows.
Fixes #657
=> r.connectivity.corridors: Use default number of files limit

.github/workflows/ci.yml
While reading the CI build output, I observed that the names of the checkout steps for the action "checkout@v2" were inverted for the last two years. I checked the[ actions documentation](https://github.com/actions/checkout) to make sure, and it was indeed an inversion.
So the simple fix is changing the names (labels), so it should be non-breaking if I didn't miss anything.
=> CI: Fix names of checkout steps for core and addons inversion

src/raster/r.area.createweight/r.area.createweight.html
Follow-up to #646, adding instructions for installing dependencies with macOS app bundles.
=> r.area.createweight manual: add macOS dependency instructions

src/raster/r.in.nasadem/r.in.nasadem.py
This PR fixes the Python error `NameError: name 'srid' is not defined`:
```
GRASS eu_laea_epsg3035/nasadem:~ > 
r.in.nasadem user=xxxx password=yyyyy output=nasadem memory=4000 method=bilinear_f resolution=30
File "/home/mundialis/.grass8/addons/scripts/r.in.nasadem", line 645, in <module>
main()
File "/home/mundialis/.grass8/addons/scripts/r.in.nasadem", line 490, in main
SRCGISRC, TMPLOC = createTMPlocation()
File "/home/mundialis/.grass8/addons/scripts/r.in.nasadem", line 350, in createTMPlocation
currepsg = ":".join(srid.split(":")[-1:])
NameError: name 'srid' is not defined
ERROR: Region <r_in_nasadem_region_285028> not found
Error in atexit._run_exitfuncs:
File …
```
=> r.in.nasadem: fix name 'srid' is not defined

src/raster/r.mapcalc.tiled/r.mapcalc.tiled.html, src/raster/r.mapcalc.tiled/r.mapcalc.tiled.py, src/raster/r.mapcalc.tiled/tests/test.py
=> r.mapcalc.tiled: use option nprocs instead of processes in backwards compatible way

src/vector/v.to.rast.multi/Makefile, src/vector/v.to.rast.multi/testsuite/test_rasterize_multi.py, src/vector/v.to.rast.multi/v.to.rast.multi.html, src/vector/v.to.rast.multi/v.to.rast.multi.py
This new module is a simple wrapper around v.to.rast to create raster maps for multiple attributes in an efficient way. Should save both time and storage.
It works with GRASS GIS 7 as well, so backporting might be appropriate....
=> v.to.rast.multi: create raster maps for multiple attributes of a vector map

utils/cronjobs_osgeo_lxd/compile_addons_git.sh, utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
Fixes #601. G7 addons manual page source code and history URL is wrong pointed to grass7 git branch (the bug only affects addons manual html pages builded on the osgeo lxd server container).
=> utils/cronjobs_osgeo_lxd: fix G7/G8 addons manual page source code and history URL git branch

src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
This adds the bandref directly to the raster map. I think if would also have been written upon registration in the temporal database but this way it is available without using temporal modules...
As discussed in #609
=> i.sentinel.import: write semantic label with r.support

src/raster/r.colors.out_sld/r.colors.out_sld.py
Avoid Python error if the input map doesn't exist.
=> r.colors.out_sld: check if input map exists

src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Timestamp format string `%-d %b %Y %H:%M:%S.%f` works on Linux (Python 3.9.10) but fails on Windows (Python 3.9.5) with
```
ValueError: Invalid format string
```
=> i.sentinel.import fails on Windows with Invalid format string

src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
`i.sentinel.import` creates on Windows register output file with empty lines:
```
T32UPB_20190407T102021_B04_10m|2019-04-07 10:26:45.035007|S2_4
T32UPB_20190407T102021_B08_10m|2019-04-07 10:26:45.035007|S2_8
```
which leads to problem with registering maps into space-time dataset:
```
t.create output=sentinel title="Sentinel L2A 2019" desc="Jena region"
t.register input=sentinel file=z:\timestamps.txt
t.info input=sentinel
...
| Number of registered maps:.. 1
```
This PR replaces `os.linesep` with `\n`. From Python docs:
```
Do not use os.linesep as a line terminator when writing files opened in text mode (the default); use a single '\n' instead, on all platforms.
```
=> i.sentinel.import: os.linesep -> \n

src/imagery/i.modis/i.modis.import/i.modis.import.py
`i.modis.import` fails in GRASS 8 by
```
ERORR: GRASS GIS version 7 required
```
This PR removes version check completely since in `grass8` branch we are expecting code compatible with GRASS 8.
=> i.modis.import: remove grass version check

src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Better guide the user to the problem when specifying a SAFE file instead of the containing directory:
Before:
```
GRASS utm32N_32632/bonn:bonn_dgm1 > i.sentinel.import -p input=~/tmp/s2_data/S2A_MSIL2A_20211009T103941_N0301_R008_T32ULB_20211009T134536.SAFE.zip  --verbose
ERROR: Nothing found to import. Please check input and pattern_file
options.
```
Now, with this PR:
```
GRASS utm32N_32632/bonn:bonn_dgm1 > i.sentinel.import -p input=~/tmp/s2_data/S2A_MSIL2A_20211009T103941_N0301_R008_T32ULB_20211009T134536.SAFE 
ERROR: No Sentinel files found to import in directory
</home/mneteler/tmp/s2_data/S2A_MSIL2A_20211009T103941_N0301_R008_T32ULB_20211009T134536.SAFE>.
Please check input and pattern_file options.
```
=> i.sentinel.import: less obscure error message

src/imagery/i.fusion.hpf/i.fusion.hpf.py
Fixes (when `suffix` is not used) confusing warning:
`WARNING: Illegal filename <.hpf>. Cannot start with '.' or be 'NULL'.`
(In the parser `answer` no trailing dot may be used).
=> i.fusion.hpf: fix "Illegal filename <.hpf>" warning

utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_job_list_grass
- adds G8.dev binary cronjob which creates the manual pages as well: 
https://grass.osgeo.org/grass-devel/manuals/index.html
Note: Once merged, it requires deploment on server with `crontab ...`.
=> cronjobs: add GRASS GIS main branch binary build job

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/grass-addons-index.sh
This PR injects a red box into the [G78 manual pages](https://grass.osgeo.org/grass78/manuals/), pointing to the respective G80 manual page.
This is added to all G78 manual pages.
In addition, it adds minor version number to addon manual landing page title to reduce confusion.
=> G78 cronjobs: add "new version G8" box into man pages

src/imagery/i.landsat/i.landsat.import/i.landsat.import.html, src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.html
(minor fix; redirects are in place on grass.osgeo.org)
=> manual: g.bands has been renamed to i.band.library

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
This PR injects a red box into the G78 addon manual pages, pointing to the respective G80 addon manual page.
It completes #718.
Random example:
=> G78 addon cronjob: add "new version G8" box into addon man pages

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
This PR finetunes the message wording in the box.
Additionally, the addon landing page now also gets a box injected ("This addon documentation is ...").
Addresses comment in https://github.com/OSGeo/grass-addons/pull/731#issuecomment-1105617844
Random pick:
=> G78 addon cronjob: update "new version G8" box

src/raster/r.catchment/r.catchment.py
Fixes failure of r.catchment, likely introduced by changes in Python 3.
```
r.catchment --overwrite elevation=elev_srtm_30m@PERMANENT start_points=startinsite@user1 buffer=catchmentbuff area=5000000 map_val=1
WARNING: Bug in UI description. Description for option <b> missing
WARNING: Bug in UI description. Description for option <c> missing
WARNING: Bug in UI description. Description for option <d> missing
Wanted buffer area=5000000
File "/Users/nila/Library/GRASS/7.9/Modules/scripts/r.c
atchment", line 379, in <module>
main()
File "/Users/nila/Library/GRASS/7.9/Modules/scripts/r.c
atchment", line 294, in main
out2dictnum('r.stats -Aani input=' + cost +
File "/Users/nila/Library/GRASS/7.9/Modules/scripts/r.c
atchment", line 147, in out2dictnum
y0, y1 = …
```
=> r.catchment: read stdout as text, Python 3 update

utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
After https://github.com/OSGeo/grass/pull/2316 now the i18N .pot files must not be generated any more in this cronjob, to avoid an git update error.
Currently only applies to G8.1 cronjob.
=> cron_grass8_main_build_binaries.sh: no longer generate i18N .pot files

src/vector/v.stream.profiler/v.stream.profiler.py
This PR adds a try-except for `matplotlib` import to avoid compilation failure on the Addons server (https://grass.osgeo.org/addons/grass8/logs/). To be backported to G7 addons.
=> v.stream.profiler: try-except for matplotlib import

src/raster/r.boxplot/r.boxplot.html, src/raster/r.boxplot/r.boxplot.py
The r.colors.out, used to extract the color table of the zonal map, sometimes returns a color table with floating category id's instead of integers. I assume this is when the raster layer has no color table defined? The change checks if the category id's are of the type integer. If not, a more informative error message is returned.
In addition, a new option to set the boxplot width(s) is added, and the manual page is updated accordingly.
=> r.boxplot better error handling

utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_job_list_grass
- updated cronjob to build GRASS 8.2 binaries + addons from the `releasebranch_8_2` branch
- bump G8.1 to G8.3 (main branch) in crontab
Once GRASS GIS 8.2.0 has been released, this cronjob change PR needs to be merged and the updated `crontab` be deployed on the GRASS GIS server (osgeo8-grass; see https://github.com/OSGeo/grass/blob/main/doc/infrastructure.md#grass-web-server). @neteler will take care of that.
=> cron_grass8_relbranch_build_binaries.sh: update to GRASS GIS 8.2 stable

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/grass-addons-index.sh
**Describe the bug**
Wrong MS Windows Addons compilation log files URL link
**To Reproduce**
Steps to reproduce the behavior:
1. Open in web browser Addons manuals URL https://grass.osgeo.org/grass82/manuals/addons/
2. Click on the [Windows log files](https://wingrass.fsv.cvut.cz/grass82/x86_64/addons/grass-8.2.dev/logs/)
3. See error
**Expected behavior**
Correct MS Windows Addons compilation log files URL link
=> utils/cronjobs_osgeo_lxd: fix MS Windows Addons compilation log files URL link

src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
Using `i.sentinel.import` in a lat/lon location (or any location that does not have meters as projection units) fails as the `resolution_value` parameter for `r.import` is read from the band metadata (which is in metres, e.g. `10`, `20`, `60`), so a final reprojected map will be empty. 
This PR adapts `i.sentinel.import` such that it only applies the `resolution_value` parameter to `r.import` if the location units are `meters`
=> i.sentinel.import: allow importing for lat/lon locations

src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py
If - like in the NC sample dataset - the unit in the `PROJ_UNITS` file is written with a capital letter the resolution detection fails.
```
GRASS nc_spm_08_grass7/sentinel2:foss4g_grass4rs > g.proj -p
-PROJ_INFO-------------------------------------------------
name       : Lambert Conformal Conic
proj       : lcc
...
-PROJ_SRID-------------------------------------------------
SRID       : EPSG:3358
-PROJ_UNITS------------------------------------------------
unit       : Meter
units      : Meters
meters     : 1
```
Completes PR #769.
=> i.sentinel.import: fix unit test (capital letter)

src/raster/r.learn.ml2/r.learn.predict/r.learn.predict.py
Avoid crash when category labels contain a comma as e.g. in US NLCD Land cover product
... by changing the separator from comma to pipe character.
(see https://grasswiki.osgeo.org/wiki/NLCD_Land_Cover#Legend)
=> r.learn.ml2: fix r.category call in r.learn.predict

src/raster/r.mapcalc.tiled/r.mapcalc.tiled.py
By calculating the example with GRASS 8.0 I get the following error:
```
r.mapcalc.tiled expression="bright_pixels = if(ortho_2001_t792_1m > 200, 1, 0)"    width=1000 height=1000 nprocs=4
File "/home/aweinmann/.grass8/addons/scripts/r.mapcalc.tiled", line 227, in <module>
main()
File "/home/aweinmann/.grass8/addons/scripts/r.mapcalc.tiled", line 211, in main
grd = MyGridModule(
File "/home/aweinmann/repos/grass/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/modules/grid/grid.py", line 518, in __init__
self.bboxes = split_region_tiles(
File "/home/aweinmann/repos/grass/grass/dist.x86_64-pc-linux-gnu/etc/python/grass/pygrass/modules/grid/split.py", line 78, in split_region_tiles
ncols = (reg.cols + width - 1) // width
TypeError: unsupported …
```
=> r.mapcalc.tiled: width and heigt as int

src/imagery/i.sentinel/i.sentinel.parallel.download/i.sentinel.parallel.download.py
This PR allows `i.sentinel.parallel.download` to directly download from GCS if the sentinel-2 scene names are specified via the `-s `flag and if **no settings file is provided**. This specific case is already possible in `i.sentinel.download` but so far the `settings` parameter was required in `i.sentinel.parallel.download`
=> i.sentinel.parallel.download: allow download from GCS with scenename specifications and without credentials

src/raster/r.mapcalc.tiled/r.mapcalc.tiled.py
=> r.mapcalc.tiled: fix not change MAPSET search path

utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
Implement (closes) #776. Before apply this PR, you have to apply this GRASS GIS [PR](https://github.com/OSGeo/grass/pull/2529), please.
=> utils/cronjobs_osgeo_lxd: allow register all addons keywords in main Keywords Index

utils/cronjobs_osgeo_lxd/hugo_clean_and_update_job.sh
Local file linking of sitemap.xml no longer needed after https://github.com/OSGeo/grass-website/pull/318
=> hugo_clean_and_update_job.sh: remove superfluous sitemap link

src/temporal/t.rast.boxplot/t.rast.boxplot.html
Removing reference to wrong image in examples
=> t.rast.boxplot correction manual page

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/robots.txt
SEO fixes (improve ranking of GRASS GIS 8.2 manual pages over 7.8):
- define canonical manual URL (grass-stable) in `cron_grass7_relbranch_build_binaries.sh`
- follows: https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls
- do not disallow crawling of even GRASS GIS version manual pages in `robots.txt`
Minor fixes: fix duckduckgo search syntax in `cron_grass*_build_binaries.sh`
=> SEO: define canonical URL in older manual pages; robots.txt tweaks

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
SEO fixes (improve ranking of GRASS GIS 8.2 manual pages over 7.8) for
- addon manuals
- libpython manuals
Completes #800
=> SEO: define canonical URL in older addon and libpython manuals

src/temporal/t.rast.patch/t.rast.patch.html, src/temporal/t.rast.patch/t.rast.patch.py
Using the virtual raster format (`r.buildvrt`) should provide a reduction in both processing time and storage usage.
For some workflows a virtual raster may be good enough.
I have not yet fully tested the modifications though...
=> t.rast.patch: allow use of virtual format

.github/workflows/ci.yml
Python code doesn't interpret wildcard `*` inside path. Fixes #803.
=> .github/workflows: fix `MODULE_TOPDIR` ENV var path value

src/imagery/i.sentinel/i.sentinel.parallel.download/i.sentinel.parallel.download.py
CPU count function and data source option were not referenced correctly.
=> i.sentinel.parallel.download: Fix CPU count and options access

.github/workflows/ci.yml
r.futures.potential uses MuMIn R package which requires >= 4.2.0. Upgrading from 4.0.4 to latest 4.2.1 should fix that.
=> CI: upgrade to latest R to fix test

src/vector/v.db.pyupdate/testsuite/test_v_db_pyupdate.py, src/vector/v.db.pyupdate/v.db.pyupdate.py
At one point during development v.db.select used -j flag for json output, but it was changed to format=json before release. v.db.pyupdate was using the old syntax. Tests are also updated, so they should run now.
=> v.db.pyupdate: fix to use latest v.db.select format=json option

src/imagery/i.segment.hierarchical/i.segment.hierarchical.py, src/imagery/i.segment.stats/i.segment.stats.py, src/imagery/i.segment.uspo/i.segment.uspo.py, src/imagery/i.spec.sam/main.c, src/raster/r.gdd/main.c, src/raster/r.in.usgs/r.in.usgs.py, src/raster/r.learn.ml/r.learn.ml.py, src/raster/r.learn.ml2/r.learn.train/r.learn.train.py, src/raster/r.massmov/main.c, src/raster/r.maxent.lambdas/r.maxent.lambdas.py, src/raster/r.shaded.pca/r.shaded.pca.py, src/raster/r.sim.terrain/r.sim.terrain.py, src/raster/r.sun.daily/r.sun.daily.py, src/raster/r.sun.hourly/r.sun.hourly.py, src/raster/r.survey/r.survey.py, src/raster/r.tpi/r.tpi.py, src/raster/r.tri/r.tri.py, src/raster/r.vector.ruggedness/r.vector.ruggedness.py, src/raster/r.viewshed.exposure/r.viewshed.exposure.py, src/temporal/t.rast.null/t.rast.null.py, src/temporal/t.rast.what.aggr/t.rast.what.aggr.py
* Adds parallel keyword to modules which use multiprocessing for parallel runs.
* Adds parallel keyword to modules which use OpenMP in C.
* No new keyword for r.futures, i.ann.maskrcnn, r.pops.spread, r.sun.mp, r.sim.water.mp.
* Remove unused multiprocessing and other unused imports from r.tpi.
* Adds or fixes keywords when missing or using keywords instead of keywords.
* Add aggregation as topic keyword for r.gdd (based on r.series topic keyword).
* Fixes obvious typos in non-code in modified files.
=> Add parallel keyword for multiprocessing and OpenMP

src/imagery/i.gabor/i.gabor.py
Lazy import py packages must be called after call `grass.parser()` function.
`scipy` py package is not available.
```
GRASS nc_spm_08_grass7/landsat:~ > g.extension i.gabor
Fetching <i.gabor> from GRASS GIS Addons repository (be patient)...
Compiling...
ERROR: Cannot import fftconvolve from scipy
make: *** [/usr/lib64/grass83/include/Make/Html.make:14: i.gabor.tmp.html] Error 1
ERROR: Compilation failed, sorry. Please check above error messages.
```
**Expected behavior:**
The addon installation should work even if the scipy py package is not available.
=> i.gabor: fix lazy import py packages

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
Fix currently broken paths to grass-stable redirects.
=> cron_grass7_binaries: fix relative path in red redirect box in G78 manuals

src/general/g.citation/g.citation.py, src/general/g.citation/testsuite/test_g_citation.py
Replace #677 that was accidentally closed
=> g.citation: update regex to get date and author from manual

src/general/g.citation/g.citation.py, src/general/g.citation/testsuite/test_g_citation.py
Fix module `output` parameter.
**Current behavior**
```bash
GRASS nc_spm_08_grass7/landsat:~ > g.citation v.surf.rst output=/tmp/result
GRASS nc_spm_08_grass7/landsat:~ > file /tmp/result
/tmp/result: cannot open `/tmp/result' (No such file or directory)
```
**Expected behavior:**
```bash
GRASS nc_spm_08_grass7/landsat:~ > g.citation v.surf.rst output=/tmp/result 
GRASS nc_spm_08_grass7/landsat:~ > cat /tmp/result 
@misc{v_surf_rst,
title = {{GRASS GIS: v.surf.rst module}},
author = {Lubos Mitas and Helena Mitasova and Irina Kosinovsky and Darrel McCauley and Jaroslav Hofierka and Stanislav Zubal and Michal Lacko},
howpublished = {https://github.com/OSGeo/grass/tree/main/vector/v.surf.rst},
year = {2022}
note = {Accessed: 2022-10-16T07:02:16},
}
```
=> g.citation: fix module output parameter

.github/workflows/ci.yml
See https://github.com/OSGeo/grass-addons/pull/819#issuecomment-1287415722.
=> .github/workflows: remove build old stable GRASS GIS 8.0 version from the CI

utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_grass8_relbranch_build_binaries.sh
Fixes https://github.com/OSGeo/grass/pull/2606#issuecomment-1288098566.
=> utils/cronjobs_osgeo_lxd: copy addon HTML man page hamburger menu TOC SVG images to the addons dir

utils/cronjobs_osgeo_lxd/cron_grass8_main_build_binaries.sh
Fixed by https://github.com/OSGeo/grass/pull/2354
=> utils/cronjobs_osgeo_lxd: remove redundant cleanup of __pycache__ dirs

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh, utils/cronjobs_osgeo_lxd/cron_job_list_grass
- Since the canonical was overwritten during addon compilation, a second (modified) injection in the cronjob
- shift timings of cronjobs to avoid overlaps
=> SEO GRASS GIS 7 manual: properly inject canonical

src/raster/r.series.boxplot/r.series.boxplot.html, src/temporal/t.rast.boxplot/t.rast.boxplot.html
HTML manuals for currently fail to build, see:
https://grass.osgeo.org/addons/grass8/logs/
This PR attempts to addresses those issues and with the proposed changes HTML manuals build locally:
`python3 /opt/src/grass/dist.x86_64-pc-linux-gnu/utils/mkhtml.py t.rast.boxplot`
=> r.series.boxplot / t.rast.boxplot: html manual fixes

src/raster/r.in.nasadem/r.in.nasadem.py
This PR fixes #821:
- Any connection error for the download of nasadem tiles is now properly caught and reported using the generic [urllib.error.URLError](https://docs.python.org/3/library/urllib.error.html)
- A bug in the cleanup function is fixed: The region is saved in the original location/mapset, but at the beginning of the cleanup function, we may still be in the temp location. This resulted in errors of `g.remove type=region...`
=> r.in.nasadem: catch http error

utils/cronjobs_osgeo_lxd/cron_grass7_relbranch_build_binaries.sh
Change canoncial URL from `grass-stable` to `grass82` to clearly mark grass82 as the (currently) relevant manual pages.
Disadvantage: cronjob needs to be updated once the next stable has been released.
Ideally avoid lack of indexing of G82 manual pages. Currently Google  does not index G82 manual pages and keeps boosting G78:
**Overview:**
**Example:**
Once this PR is merged I'll request Google to re-index the G82 manual pages.
=> SEO grass78 manual canoncial URL: point to grass82 not grass-stable

src/temporal/t.rast.boxplot/t.rast.boxplot.html, src/temporal/t.rast.boxplot/t.rast.boxplot.py
Adds the option to let the function select the best date format (uses the matplotlib functions ConciseDateFormatter and AutoDateLocator). Update help file.
=> t.rast.boxplot: concise label option added 

src/raster/r.pi/r.pi.corearea/Makefile, src/raster/r.pi/r.pi.csr.mw/Makefile, src/raster/r.pi/r.pi.energy.pr/Makefile, src/raster/r.pi/r.pi.energy/Makefile, src/raster/r.pi/r.pi.enn.pr/Makefile, src/raster/r.pi/r.pi.enn/Makefile, src/raster/r.pi/r.pi.export/Makefile, src/raster/r.pi/r.pi.fnn/Makefile, src/raster/r.pi/r.pi.graph.dec/Makefile, src/raster/r.pi/r.pi.graph.pr/Makefile, src/raster/r.pi/r.pi.graph.red/Makefile, src/raster/r.pi/r.pi.graph/Makefile, src/raster/r.pi/r.pi.import/Makefile, src/raster/r.pi/r.pi.index/Makefile, src/raster/r.pi/r.pi.neigh/Makefile, src/raster/r.pi/r.pi.nlm.circ/Makefile, src/raster/r.pi/r.pi.nlm.stats/Makefile, src/raster/r.pi/r.pi.nlm/Makefile, src/raster/r.pi/r.pi.odc/Makefile, src/raster/r.pi/r.pi.prob.mw/Makefile, src/raster/r.pi/r.pi.prox/Makefile, src/raster/r.pi/r.pi.searchtime.mw/Makefile, src/raster/r.pi/r.pi.searchtime.pr/Makefile, src/raster/r.pi/r.pi.searchtime/Makefile
This PR adds the version number to `-lgrass_rpi` to support MinGW compilation on Windows.
=> r.pi: Add GRASS_LIB_VERSION_NUMBER to LIB_NAME for Windows

src/imagery/i.pr/PRLIB/bootstrap.c, src/imagery/i.pr/PRLIB/svm.c, src/imagery/i.pr/i.pr_blob/Makefile, src/imagery/i.pr/i.pr_classify/Makefile, src/imagery/i.pr/i.pr_features/Makefile, src/imagery/i.pr/i.pr_features_additional/Makefile, src/imagery/i.pr/i.pr_features_extract/Makefile, src/imagery/i.pr/i.pr_features_selection/Makefile, src/imagery/i.pr/i.pr_model/Makefile, src/imagery/i.pr/i.pr_sites_aggregate/Makefile, src/imagery/i.pr/i.pr_statistics/Makefile, src/imagery/i.pr/i.pr_subsets/Makefile, src/imagery/i.pr/i.pr_training/Makefile, src/imagery/i.pr/i.pr_uxb/Makefile
This PR enables compilation of i.pr modules for Windows (except some modules that use old header files).
=> i.pr: Replace drand48() with G_drand48(), Add lib version to -lgrass_pr for Windows

src/raster/r.accumulate/main.c
This PR allows subwatershed calculation with accumulated longest flow path (-a). They are not computationally exclusive.
=> r.accumulate: Allow subwatershed= with -a

.github/workflows/black.yml, .github/workflows/ci.yml, .github/workflows/flake8.yml, .github/workflows/super-linter.yml
The GHA `ci.yml` and others show the warning
_Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2, r-lib/actions/setup-r@v1, actions/upload-artifact@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/._
Additionally:
- update the various actions
- updates ubuntu-20.04 to ubuntu-22.04 (see also https://github.com/OSGeo/grass/pull/2730)
- sync Python to v3.10
- updates to super-linter:v4
- super-linter: enable markdown linting
- use the real super-linter action instead of a container
- super-linter.yml: do not mix VALIDATE=true and VALIDATE=false
=> GitHub actions: update to current versions

.github/ISSUE_TEMPLATE/bug_report.md, README.md, src/imagery/i.fusion.hpf/README.md, src/imagery/i.landsat8.swlst/README.md, src/raster/r.estimap.recreation/README.md, src/raster/r.findtheriver/README.md, src/raster/r.landscape.evol/r.landscape.evol.md, src/raster/r.mapcalc.tiled/tests/README.md, src/raster/r.mblend/README.md, src/raster/r.pops.spread/README.md, src/raster/r.pops.spread/pops-core/CHANGELOG.md, src/raster/r.pops.spread/pops-core/README.md, src/raster/r.pops.spread/pops-core/TECHNICALDEBT.md, src/raster/r.pops.spread/pops-core/contributing_docs/CODE_OF_CONDUCT.md, src/raster/r.pops.spread/pops-core/contributing_docs/CONTRIBUTING.md, src/raster/r.pops.spread/pops-core/contributing_docs/STYLE_GUIDE.md, utils/cronjobs_osgeo_lxd/README.md
All markdown files are formatted and now passes [markdownlint](https://github.com/igorshubovych/markdownlint-cli).
=> markdown: fix lint errors

src/imagery/i.sentinel/i.sentinel.import/i.sentinel.import.py, src/raster/r.mess/r.mess.py, src/raster/r.object.activelearning/r.object.activelearning.py, src/vector/v.class.ml/ml_functions.py
Replace np.float (numpy.float) by float (np.float is an alias for python float type), since it does not exist anymore in numpy (version 1.24.1).
Please see https://github.com/OSGeo/grass-addons/issues/856 for more details.
=> Replace np.float (numpy.float) by float

src/raster/r.confusionmatrix/r.confusionmatrix.html, src/raster/r.confusionmatrix/r.confusionmatrix.py, src/raster/r.confusionmatrix/testsuite/data/confusionmatrix_raster_matrix.csv, src/raster/r.confusionmatrix/testsuite/data/confusionmatrix_raster_matrix_oneclass.csv, src/raster/r.confusionmatrix/testsuite/test_r_confusionmatrix.py
Fix tests by adjust result data after `r.kappa` change.
Solves [831](https://github.com/OSGeo/grass-addons/issues/831)
=> r.confusionmatrix: fix tests

src/vector/v.transects/v.transects.html, src/vector/v.transects/v.transects.py
This allows reference of the output transects to the original lines, which is essential in many applications of transects. The way to get the categories of the input lines into the transect table, also added to the docs:
```
v.transects input=lines output=transects transect_spacing=100
v.db.addtable transects columns="line_cat"
v.db.addtable transects layer=2
v.to.db transects query_layer=2 query_column=cat option=query column=line_cat
```
I have also updated the _type_ parameter description to say that it determines the output type rather than the input as it says now.
=> v.transects: Add categories of input lines to layer 2 of output
